/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminConfig {
  'newsletterEnabled' : boolean,
  'appVersion' : string,
  'senderName' : string,
  'senderEmail' : string,
}
export interface AdminConfigInput {
  'newsletterEnabled' : boolean,
  'appVersion' : string,
  'senderName' : string,
  'senderEmail' : string,
}
export interface Badge {
  'id' : string,
  'name' : string,
  'description' : string,
  'earnedAt' : bigint,
  'iconGlyph' : string,
}
export interface Cell { 'value' : Value, 'name' : string }
export interface Chapter {
  'id' : bigint,
  'verseCount' : bigint,
  'name' : string,
  'summary' : string,
}
export interface ConcentrationSession {
  'id' : string,
  'completedAt' : bigint,
  'sessionType' : string,
  'durationMinutes' : bigint,
  'principalId' : string,
}
export interface DailyChallenge {
  'action' : string,
  'date' : string,
  'task' : string,
  'points' : bigint,
}
export interface DailyDuty {
  'id' : string,
  'sourceGranth' : string,
  'sourceChapter' : string,
  'timing' : string,
  'sanskritName' : string,
  'name' : string,
  'description' : string,
  'sourceVerse' : string,
  'linkedExplanationId' : string,
  'practice' : string,
  'category' : string,
}
export interface DashaEntry {
  'durationYears' : number,
  'endDate' : bigint,
  'lord' : string,
  'startDate' : bigint,
}
export interface DateOfBirth {
  'day' : bigint,
  'month' : bigint,
  'year' : bigint,
}
export interface DevlokStage {
  'id' : string,
  'sourceGranth' : string,
  'sourceChapter' : string,
  'sanskritName' : string,
  'stageNumber' : bigint,
  'name' : string,
  'description' : string,
  'sourceVerse' : string,
  'significance' : string,
}
export interface DharmaBodhStep {
  'id' : string,
  'sourceGranth' : string,
  'title' : string,
  'sourceChapter' : string,
  'sanskritName' : string,
  'question' : string,
  'sourceVerse' : string,
  'stepNumber' : bigint,
  'practice' : string,
  'guidance' : string,
}
export interface DharmaPillar {
  'id' : string,
  'sourceGranth' : string,
  'sourceChapter' : string,
  'sanskritName' : string,
  'name' : string,
  'description' : string,
  'sourceVerse' : string,
  'practice' : string,
}
export interface DikshaVidhi {
  'id' : string,
  'sourceGranth' : string,
  'sourceChapter' : string,
  'sanskritName' : string,
  'prerequisites' : Array<string>,
  'name' : string,
  'description' : string,
  'sourceVerse' : string,
  'mantra' : string,
  'procedure' : Array<string>,
}
export interface DonationInfo {
  'qrCodeAssetId' : string,
  'ifscCode' : string,
  'bankName' : string,
  'updatedAt' : bigint,
  'accountName' : string,
  'upiId' : string,
  'accountNumber' : string,
}
export interface DonationInfoInput {
  'qrCodeAssetId' : string,
  'ifscCode' : string,
  'bankName' : string,
  'accountName' : string,
  'upiId' : string,
  'accountNumber' : string,
}
export interface EmailSubscriber {
  'active' : boolean,
  'subscribedAt' : bigint,
  'name' : string,
  'email' : string,
}
export type ExternalBlob = Uint8Array;
export interface Festival {
  'sourceGranth' : string,
  'dateStr' : string,
  'sourceChapter' : string,
  'meaning' : string,
  'name' : string,
  'sourceVerse' : string,
  'story' : string,
  'mantraName' : string,
  'recommendedVerse' : string,
}
export interface GalleryImageInput {
  'asset' : ExternalBlob,
  'caption' : string,
  'category' : string,
}
export interface GalleryImageMeta {
  'id' : bigint,
  'isApproved' : boolean,
  'asset' : ExternalBlob,
  'caption' : string,
  'category' : string,
  'uploader' : Principal,
  'uploadedAt' : bigint,
}
export interface GrahaRemedyData {
  'avoidList' : Array<string>,
  'daan' : string,
  'role' : string,
  'mantraSanskrit' : string,
  'mantraCount' : bigint,
  'gemstone' : string,
  'graha' : string,
  'weakCauses' : Array<string>,
  'gemstoneWarning' : string,
  'remedies' : Array<string>,
  'strongGives' : Array<string>,
}
export interface Granth {
  'id' : string,
  'sanskritName' : string,
  'sourceCitation' : string,
  'name' : string,
  'granthType' : GranthType,
  'description' : string,
  'totalChapters' : bigint,
}
export interface GranthChapter {
  'sanskritName' : string,
  'verseCount' : bigint,
  'name' : string,
  'chapterId' : bigint,
  'summary' : string,
  'granthId' : string,
}
export type GranthType = { 'gita' : null } |
  { 'veda' : VedaName } |
  { 'purana' : PuranaName } |
  { 'upanishad' : UpanishadName };
export interface GranthVerse {
  'sourceGranth' : string,
  'sourceChapter' : bigint,
  'verseNumber' : string,
  'sourceVerse' : string,
  'chapterId' : bigint,
  'verseId' : bigint,
  'sanskritDevanagari' : string,
  'simpleMeaning' : string,
  'sanskritTransliteration' : string,
  'granthId' : string,
}
export interface GuidanceResult {
  'guidanceText' : string,
  'verse' : bigint,
  'keyword' : string,
  'chapter' : bigint,
}
export interface HeatmapEntry {
  'allGoalsMet' : boolean,
  'chaptersRead' : bigint,
  'date' : string,
  'versesRead' : bigint,
  'principalId' : string,
}
export interface JournalEntry {
  'id' : string,
  'mood' : string,
  'createdAt' : bigint,
  'text' : string,
  'verseId' : string,
  'updatedAt' : bigint,
  'principalId' : string,
}
export interface KarmaType {
  'id' : string,
  'sourceGranth' : string,
  'sourceChapter' : string,
  'sanskritName' : string,
  'name' : string,
  'description' : string,
  'sourceVerse' : string,
  'practice' : string,
}
export interface KundliData {
  'navamsaLagnaSign' : bigint,
  'pratyantarDasha' : DashaEntry,
  'lagnaRashi' : string,
  'profileId' : Principal,
  'rulingPlanetGlyph' : string,
  'lagnaSign' : bigint,
  'calculatedAt' : bigint,
  'planets' : Array<PlanetPlacement>,
  'rulingPlanet' : string,
  'antardasha' : DashaEntry,
  'navamsaPlanets' : Array<PlanetPlacement>,
  'nextDashas' : Array<DashaEntry>,
  'mahadasha' : DashaEntry,
}
export interface LastRiteStep {
  'id' : string,
  'sourceGranth' : string,
  'title' : string,
  'sourceChapter' : string,
  'sanskritName' : string,
  'description' : string,
  'sourceVerse' : string,
  'stepNumber' : bigint,
  'mantra' : string,
  'procedure' : string,
}
export interface LeaderboardEntry {
  'donorName' : string,
  'rank' : bigint,
  'lastDonationAt' : bigint,
  'totalDonation' : bigint,
  'donorPrincipal' : string,
  'donationCount' : bigint,
}
export type MantraCategory = { 'sharanam' : null } |
  { 'protection' : null } |
  { 'mahamantra' : null } |
  { 'general' : null };
export interface MantraEntry {
  'id' : string,
  'meaning' : string,
  'name' : string,
  'text' : string,
  'category' : MantraCategory,
  'benefit' : string,
  'recommendedCount' : bigint,
}
export interface MaunaPractice {
  'id' : string,
  'sourceGranth' : string,
  'duration' : string,
  'sourceChapter' : string,
  'sanskritName' : string,
  'name' : string,
  'description' : string,
  'sourceVerse' : string,
  'benefits' : Array<string>,
}
export interface MokshaTeaching {
  'id' : string,
  'sourceGranth' : string,
  'sourceChapter' : bigint,
  'verse' : string,
  'sourceVerse' : string,
  'sanskritDevanagari' : string,
  'chapter' : bigint,
  'simpleMeaning' : string,
  'commentary' : string,
  'sanskritTransliteration' : string,
}
export interface NaamPledge {
  'displayName' : string,
  'pledgedAt' : bigint,
  'completedCount' : bigint,
  'isActive' : boolean,
  'lastUpdatedAt' : bigint,
  'pledgedCount' : bigint,
  'mantraName' : string,
  'principalId' : string,
}
export interface PanchangData {
  'tithi' : string,
  'date' : string,
  'masa' : string,
  'ritu' : string,
  'vaar' : string,
  'yoga' : string,
  'moonSign' : string,
  'description' : string,
  'nakshatra' : string,
  'paksha' : string,
  'karana' : string,
  'tithiNumber' : bigint,
}
export interface PitruRite {
  'id' : string,
  'sourceGranth' : string,
  'offerings' : Array<string>,
  'sourceChapter' : string,
  'timing' : string,
  'sanskritName' : string,
  'name' : string,
  'description' : string,
  'sourceVerse' : string,
  'procedure' : string,
}
export interface PlanetPlacement {
  'house' : bigint,
  'planet' : string,
  'retrograde' : boolean,
  'sign' : bigint,
  'degree' : number,
  'nakshatra' : string,
  'nakshatraLord' : string,
}
export interface PregnancyWeek {
  'sourceGranth' : string,
  'title' : string,
  'sourceChapter' : string,
  'trimester' : bigint,
  'sourceVerse' : string,
  'weekNumber' : bigint,
  'saadhna' : string,
  'development' : string,
  'mantra' : string,
  'garbhaSanskarTip' : string,
}
export interface PunyaProfile {
  'currentStreakDays' : bigint,
  'badges' : Array<Badge>,
  'totalPoints' : bigint,
  'longestStreakDays' : bigint,
  'lastActivityAt' : bigint,
  'principalId' : string,
}
export type PuranaName = { 'markandeya' : null } |
  { 'brahma' : null } |
  { 'bhagavata' : null } |
  { 'narada' : null } |
  { 'agni' : null } |
  { 'vamana' : null } |
  { 'varaha' : null } |
  { 'garuda' : null } |
  { 'linga' : null } |
  { 'shiva' : null } |
  { 'brahmanda' : null } |
  { 'bhavishya' : null } |
  { 'matsya' : null } |
  { 'padma' : null } |
  { 'skanda' : null } |
  { 'kurma' : null } |
  { 'vishnu' : null } |
  { 'brahmavaivarta' : null };
export interface QuizQuestion {
  'id' : string,
  'sourceGranth' : string,
  'question' : string,
  'correctIndex' : bigint,
  'date' : string,
  'explanation' : string,
  'sourceVerse' : string,
  'options' : Array<string>,
  'points' : bigint,
}
export interface RemedyReminder {
  'isActive' : boolean,
  'reminderTime' : string,
  'graha' : string,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export interface RitualExplanation {
  'id' : string,
  'sourceGranth' : string,
  'title' : string,
  'sourceChapter' : string,
  'ritualName' : string,
  'explanation' : string,
  'sourceVerse' : string,
  'relatedDutyIds' : Array<string>,
}
export interface Sampradaya {
  'id' : string,
  'sourceGranth' : string,
  'sourceChapter' : string,
  'lineage' : Array<string>,
  'sanskritName' : string,
  'name' : string,
  'sourceVerse' : string,
  'founder' : string,
  'philosophy' : string,
}
export interface Sanskaar {
  'id' : string,
  'sourceGranth' : string,
  'sourceChapter' : string,
  'timing' : string,
  'sanskritName' : string,
  'name' : string,
  'sanskaarNumber' : bigint,
  'description' : string,
  'sourceVerse' : string,
  'significance' : string,
  'mantra' : string,
  'procedure' : Array<string>,
}
export interface SatsangCircle {
  'id' : string,
  'name' : string,
  'memberCount' : bigint,
  'description' : string,
  'iconGlyph' : string,
}
export interface SatsangMessage {
  'circleId' : string,
  'authorName' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface ShauchaPractice {
  'id' : string,
  'sourceGranth' : string,
  'sourceChapter' : string,
  'sanskritName' : string,
  'kind' : string,
  'name' : string,
  'description' : string,
  'sourceVerse' : string,
  'practice' : string,
  'benefits' : Array<string>,
}
export type SiddhiCategory = { 'kala' : null } |
  { 'mahavidya' : null } |
  { 'nidhi' : null } |
  { 'siddhi' : null };
export interface SiddhiEntry {
  'id' : string,
  'sourceGranth' : string,
  'guruDisclaimer' : string,
  'sourceChapter' : string,
  'sanskritName' : string,
  'name' : string,
  'description' : string,
  'sourceVerse' : string,
  'significance' : string,
  'category' : SiddhiCategory,
}
export interface TarotCard {
  'id' : string,
  'name' : string,
  'suit' : string,
  'reversedMeaning' : string,
  'number' : bigint,
  'uprightMeaning' : string,
  'arcana' : string,
  'imagery' : string,
  'symbolism' : string,
}
export interface TarotDraw {
  'positionName' : string,
  'cardId' : string,
  'position' : bigint,
  'isReversed' : boolean,
}
export interface TarotReading {
  'id' : string,
  'spreadType' : string,
  'question' : string,
  'interpretation' : string,
  'guidance' : string,
  'draws' : Array<TarotDraw>,
  'principalId' : string,
  'readAt' : bigint,
}
export interface TimeOfBirth { 'hour' : bigint, 'minute' : bigint }
export interface TransitEvent {
  'remedy' : string,
  'colorCode' : string,
  'endDate' : string,
  'planet' : string,
  'description' : string,
  'startDate' : string,
  'eventType' : string,
}
export type UpanishadName = { 'mundaka' : null } |
  { 'aitareya' : null } |
  { 'isha' : null } |
  { 'kena' : null } |
  { 'chandogya' : null } |
  { 'taittiriya' : null } |
  { 'brihadaranyaka' : null } |
  { 'katha' : null } |
  { 'shvetashvatara' : null } |
  { 'prashna' : null } |
  { 'mandukya' : null };
export interface UserProfile {
  'id' : Principal,
  'placeOfBirth' : string,
  'latitude' : number,
  'timezone' : string,
  'dateOfBirth' : DateOfBirth,
  'newsletterOptIn' : boolean,
  'createdAt' : bigint,
  'fullName' : string,
  'email' : string,
  'updatedAt' : bigint,
  'timeOfBirth' : TimeOfBirth,
  'longitude' : number,
  'phone' : string,
}
export interface UserProfileInput {
  'placeOfBirth' : string,
  'latitude' : number,
  'timezone' : string,
  'dateOfBirth' : DateOfBirth,
  'newsletterOptIn' : boolean,
  'fullName' : string,
  'email' : string,
  'timeOfBirth' : TimeOfBirth,
  'longitude' : number,
  'phone' : string,
}
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export type VedaName = { 'rig' : null } |
  { 'atharva' : null } |
  { 'sama' : null } |
  { 'yajur' : null };
export interface Verse {
  'id' : bigint,
  'verseNumber' : string,
  'sanskritText' : string,
  'chapterId' : bigint,
  'transliteration' : string,
  'englishTranslation' : string,
}
export interface VerseCommentary {
  'tilak' : string,
  'shankaracharya' : string,
  'verseId' : string,
  'ramanuja' : string,
}
export interface WorshipStep {
  'id' : string,
  'sourceGranth' : string,
  'sourceChapter' : string,
  'sanskritName' : string,
  'name' : string,
  'description' : string,
  'sourceVerse' : string,
  'stepNumber' : bigint,
  'mantra' : string,
  'procedure' : string,
}
export interface YugCycle {
  'id' : string,
  'sourceGranth' : string,
  'durationYears' : bigint,
  'sourceChapter' : string,
  'sanskritName' : string,
  'name' : string,
  'description' : string,
  'sourceVerse' : string,
  'characteristics' : string,
  'dharmaQuarter' : bigint,
}
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'adminListAllGalleryImages' : ActorMethod<[], Array<GalleryImageMeta>>,
  'clearOldMessages' : ActorMethod<[], undefined>,
  'createJournalEntry' : ActorMethod<[string, string, string], JournalEntry>,
  'deleteJournalEntry' : ActorMethod<[string], boolean>,
  'drawTarot' : ActorMethod<[string, string], TarotReading>,
  'execute' : ActorMethod<[string], Result>,
  'getAdminConfig' : ActorMethod<[], AdminConfig>,
  'getAllGrahaRemedies' : ActorMethod<[], Array<GrahaRemedyData>>,
  'getChapter' : ActorMethod<[bigint], [] | [Chapter]>,
  'getCircleMessages' : ActorMethod<[string], Array<SatsangMessage>>,
  'getConcentrationHistory' : ActorMethod<
    [bigint],
    Array<ConcentrationSession>
  >,
  'getDailyChallenge' : ActorMethod<[string], [] | [DailyChallenge]>,
  'getDailyDuty' : ActorMethod<[string], [] | [DailyDuty]>,
  'getDailyQuiz' : ActorMethod<[string], [] | [QuizQuestion]>,
  'getDevlokStage' : ActorMethod<[string], [] | [DevlokStage]>,
  'getDharmaBodhStep' : ActorMethod<[string], [] | [DharmaBodhStep]>,
  'getDharmaPillar' : ActorMethod<[string], [] | [DharmaPillar]>,
  'getDikshaVidhi' : ActorMethod<[string], [] | [DikshaVidhi]>,
  'getDonationInfo' : ActorMethod<[], [] | [DonationInfo]>,
  'getFestivals' : ActorMethod<[], Array<Festival>>,
  'getGalleryUploads' : ActorMethod<[], Array<GalleryImageMeta>>,
  'getGrahaRemedy' : ActorMethod<[string], [] | [GrahaRemedyData]>,
  'getGranth' : ActorMethod<[string], [] | [Granth]>,
  'getGranthChapter' : ActorMethod<[string, bigint], [] | [GranthChapter]>,
  'getGranthVerse' : ActorMethod<[string, bigint, bigint], [] | [GranthVerse]>,
  'getGuidanceByCategory' : ActorMethod<[string], [] | [GuidanceResult]>,
  'getHeatmapData' : ActorMethod<[bigint], Array<HeatmapEntry>>,
  'getJournalEntries' : ActorMethod<[], Array<JournalEntry>>,
  'getKala' : ActorMethod<[string], [] | [SiddhiEntry]>,
  'getKarmaType' : ActorMethod<[string], [] | [KarmaType]>,
  'getKrishnaGuidance' : ActorMethod<[string], [] | [GuidanceResult]>,
  'getKundliData' : ActorMethod<[], [] | [KundliData]>,
  'getLastRiteStep' : ActorMethod<[string], [] | [LastRiteStep]>,
  'getLeaderboard' : ActorMethod<[bigint], Array<LeaderboardEntry>>,
  'getMahavidya' : ActorMethod<[string], [] | [SiddhiEntry]>,
  'getMantras' : ActorMethod<[], Array<MantraEntry>>,
  'getMaunaPractice' : ActorMethod<[string], [] | [MaunaPractice]>,
  'getMokshaTeaching' : ActorMethod<[string], [] | [MokshaTeaching]>,
  'getNaamPledges' : ActorMethod<[], Array<NaamPledge>>,
  'getNidhi' : ActorMethod<[string], [] | [SiddhiEntry]>,
  'getPanchaang' : ActorMethod<[string], PanchangData>,
  'getPanchangToday' : ActorMethod<[string], PanchangData>,
  'getPitruRite' : ActorMethod<[string], [] | [PitruRite]>,
  'getPregnancyWeek' : ActorMethod<[bigint], [] | [PregnancyWeek]>,
  'getPunyaProfile' : ActorMethod<[], [] | [PunyaProfile]>,
  'getReadingStreak' : ActorMethod<[], bigint>,
  'getRemedyReminder' : ActorMethod<[], [] | [RemedyReminder]>,
  'getRitualExplanation' : ActorMethod<[string], [] | [RitualExplanation]>,
  'getSampradaya' : ActorMethod<[string], [] | [Sampradaya]>,
  'getSanskaar' : ActorMethod<[string], [] | [Sanskaar]>,
  'getSatsangCircle' : ActorMethod<[string], [] | [SatsangCircle]>,
  'getShauchaPractice' : ActorMethod<[string], [] | [ShauchaPractice]>,
  'getSiddhi' : ActorMethod<[string], [] | [SiddhiEntry]>,
  'getTarotCard' : ActorMethod<[string], [] | [TarotCard]>,
  'getTransitCalendar' : ActorMethod<[bigint], Array<TransitEvent>>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getVerse' : ActorMethod<[bigint, bigint], [] | [Verse]>,
  'getVerseCommentary' : ActorMethod<[string], [] | [VerseCommentary]>,
  'getWorshipStep' : ActorMethod<[string], [] | [WorshipStep]>,
  'getYugCycle' : ActorMethod<[string], [] | [YugCycle]>,
  'listChapters' : ActorMethod<[], Array<Chapter>>,
  'listDailyDuties' : ActorMethod<[], Array<DailyDuty>>,
  'listDevlokStages' : ActorMethod<[], Array<DevlokStage>>,
  'listDharmaBodhSteps' : ActorMethod<[], Array<DharmaBodhStep>>,
  'listDharmaPillars' : ActorMethod<[], Array<DharmaPillar>>,
  'listGranthChapters' : ActorMethod<[string], Array<GranthChapter>>,
  'listGranthVerses' : ActorMethod<[string, bigint], Array<GranthVerse>>,
  'listGranths' : ActorMethod<[], Array<Granth>>,
  'listKalas' : ActorMethod<[], Array<SiddhiEntry>>,
  'listKarmaTypes' : ActorMethod<[], Array<KarmaType>>,
  'listLastRiteSteps' : ActorMethod<[], Array<LastRiteStep>>,
  'listMahavidyas' : ActorMethod<[], Array<SiddhiEntry>>,
  'listMaunaPractices' : ActorMethod<[], Array<MaunaPractice>>,
  'listMokshaTeachings' : ActorMethod<[], Array<MokshaTeaching>>,
  'listNewsletterSubscribers' : ActorMethod<[], Array<EmailSubscriber>>,
  'listNidhis' : ActorMethod<[], Array<SiddhiEntry>>,
  'listPitruRites' : ActorMethod<[], Array<PitruRite>>,
  'listPregnancyWeeks' : ActorMethod<[], Array<PregnancyWeek>>,
  'listRitualExplanations' : ActorMethod<[], Array<RitualExplanation>>,
  'listSampradayas' : ActorMethod<[], Array<Sampradaya>>,
  'listSanskaars' : ActorMethod<[], Array<Sanskaar>>,
  'listSatsangCircleMetadata' : ActorMethod<[], Array<SatsangCircle>>,
  'listSatsangCircles' : ActorMethod<[], Array<string>>,
  'listShauchaPractices' : ActorMethod<[], Array<ShauchaPractice>>,
  'listSiddhis' : ActorMethod<[], Array<SiddhiEntry>>,
  'listTarotCards' : ActorMethod<[], Array<TarotCard>>,
  'listVerses' : ActorMethod<[bigint], Array<Verse>>,
  'listWorshipSteps' : ActorMethod<[], Array<WorshipStep>>,
  'listYugCycles' : ActorMethod<[], Array<YugCycle>>,
  'postCircleMessage' : ActorMethod<[string, string, string], undefined>,
  'recordConcentrationSession' : ActorMethod<
    [bigint, string],
    ConcentrationSession
  >,
  'recordDailyReading' : ActorMethod<
    [string, bigint, bigint, boolean],
    HeatmapEntry
  >,
  'saveKundliData' : ActorMethod<[KundliData], boolean>,
  'saveRemedyReminder' : ActorMethod<[string, string], boolean>,
  'saveUserProfile' : ActorMethod<[UserProfileInput], boolean>,
  'schema' : ActorMethod<[], string>,
  'searchJournalEntries' : ActorMethod<[string], Array<JournalEntry>>,
  'setDonationInfo' : ActorMethod<[DonationInfoInput], boolean>,
  'setGalleryImageApproval' : ActorMethod<[bigint, boolean], boolean>,
  'subscribeNewsletter' : ActorMethod<[string, string], boolean>,
  'unsubscribeNewsletter' : ActorMethod<[string], boolean>,
  'updateAdminConfig' : ActorMethod<[AdminConfigInput], boolean>,
  'updateJournalEntry' : ActorMethod<
    [string, string, string],
    [] | [JournalEntry]
  >,
  'uploadGalleryImage' : ActorMethod<[GalleryImageInput], bigint>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];