/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const GalleryImageMeta = IDL.Record({
  'id' : IDL.Nat,
  'isApproved' : IDL.Bool,
  'asset' : ExternalBlob,
  'caption' : IDL.Text,
  'category' : IDL.Text,
  'uploader' : IDL.Principal,
  'uploadedAt' : IDL.Int,
});
export const JournalEntry = IDL.Record({
  'id' : IDL.Text,
  'mood' : IDL.Text,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'verseId' : IDL.Text,
  'updatedAt' : IDL.Int,
  'principalId' : IDL.Text,
});
export const TarotDraw = IDL.Record({
  'positionName' : IDL.Text,
  'cardId' : IDL.Text,
  'position' : IDL.Nat,
  'isReversed' : IDL.Bool,
});
export const TarotReading = IDL.Record({
  'id' : IDL.Text,
  'spreadType' : IDL.Text,
  'question' : IDL.Text,
  'interpretation' : IDL.Text,
  'guidance' : IDL.Text,
  'draws' : IDL.Vec(TarotDraw),
  'principalId' : IDL.Text,
  'readAt' : IDL.Int,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const AdminConfig = IDL.Record({
  'newsletterEnabled' : IDL.Bool,
  'appVersion' : IDL.Text,
  'senderName' : IDL.Text,
  'senderEmail' : IDL.Text,
});
export const GrahaRemedyData = IDL.Record({
  'avoidList' : IDL.Vec(IDL.Text),
  'daan' : IDL.Text,
  'role' : IDL.Text,
  'mantraSanskrit' : IDL.Text,
  'mantraCount' : IDL.Nat,
  'gemstone' : IDL.Text,
  'graha' : IDL.Text,
  'weakCauses' : IDL.Vec(IDL.Text),
  'gemstoneWarning' : IDL.Text,
  'remedies' : IDL.Vec(IDL.Text),
  'strongGives' : IDL.Vec(IDL.Text),
});
export const Chapter = IDL.Record({
  'id' : IDL.Nat,
  'verseCount' : IDL.Nat,
  'name' : IDL.Text,
  'summary' : IDL.Text,
});
export const SatsangMessage = IDL.Record({
  'circleId' : IDL.Text,
  'authorName' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const ConcentrationSession = IDL.Record({
  'id' : IDL.Text,
  'completedAt' : IDL.Int,
  'sessionType' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'principalId' : IDL.Text,
});
export const DailyChallenge = IDL.Record({
  'action' : IDL.Text,
  'date' : IDL.Text,
  'task' : IDL.Text,
  'points' : IDL.Nat,
});
export const DailyDuty = IDL.Record({
  'id' : IDL.Text,
  'sourceGranth' : IDL.Text,
  'sourceChapter' : IDL.Text,
  'timing' : IDL.Text,
  'sanskritName' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sourceVerse' : IDL.Text,
  'linkedExplanationId' : IDL.Text,
  'practice' : IDL.Text,
  'category' : IDL.Text,
});
export const QuizQuestion = IDL.Record({
  'id' : IDL.Text,
  'sourceGranth' : IDL.Text,
  'question' : IDL.Text,
  'correctIndex' : IDL.Nat,
  'date' : IDL.Text,
  'explanation' : IDL.Text,
  'sourceVerse' : IDL.Text,
  'options' : IDL.Vec(IDL.Text),
  'points' : IDL.Nat,
});
export const DevlokStage = IDL.Record({
  'id' : IDL.Text,
  'sourceGranth' : IDL.Text,
  'sourceChapter' : IDL.Text,
  'sanskritName' : IDL.Text,
  'stageNumber' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sourceVerse' : IDL.Text,
  'significance' : IDL.Text,
});
export const DharmaBodhStep = IDL.Record({
  'id' : IDL.Text,
  'sourceGranth' : IDL.Text,
  'title' : IDL.Text,
  'sourceChapter' : IDL.Text,
  'sanskritName' : IDL.Text,
  'question' : IDL.Text,
  'sourceVerse' : IDL.Text,
  'stepNumber' : IDL.Nat,
  'practice' : IDL.Text,
  'guidance' : IDL.Text,
});
export const DharmaPillar = IDL.Record({
  'id' : IDL.Text,
  'sourceGranth' : IDL.Text,
  'sourceChapter' : IDL.Text,
  'sanskritName' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sourceVerse' : IDL.Text,
  'practice' : IDL.Text,
});
export const DikshaVidhi = IDL.Record({
  'id' : IDL.Text,
  'sourceGranth' : IDL.Text,
  'sourceChapter' : IDL.Text,
  'sanskritName' : IDL.Text,
  'prerequisites' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sourceVerse' : IDL.Text,
  'mantra' : IDL.Text,
  'procedure' : IDL.Vec(IDL.Text),
});
export const DonationInfo = IDL.Record({
  'qrCodeAssetId' : IDL.Text,
  'ifscCode' : IDL.Text,
  'bankName' : IDL.Text,
  'updatedAt' : IDL.Int,
  'accountName' : IDL.Text,
  'upiId' : IDL.Text,
  'accountNumber' : IDL.Text,
});
export const Festival = IDL.Record({
  'sourceGranth' : IDL.Text,
  'dateStr' : IDL.Text,
  'sourceChapter' : IDL.Text,
  'meaning' : IDL.Text,
  'name' : IDL.Text,
  'sourceVerse' : IDL.Text,
  'story' : IDL.Text,
  'mantraName' : IDL.Text,
  'recommendedVerse' : IDL.Text,
});
export const VedaName = IDL.Variant({
  'rig' : IDL.Null,
  'atharva' : IDL.Null,
  'sama' : IDL.Null,
  'yajur' : IDL.Null,
});
export const PuranaName = IDL.Variant({
  'markandeya' : IDL.Null,
  'brahma' : IDL.Null,
  'bhagavata' : IDL.Null,
  'narada' : IDL.Null,
  'agni' : IDL.Null,
  'vamana' : IDL.Null,
  'varaha' : IDL.Null,
  'garuda' : IDL.Null,
  'linga' : IDL.Null,
  'shiva' : IDL.Null,
  'brahmanda' : IDL.Null,
  'bhavishya' : IDL.Null,
  'matsya' : IDL.Null,
  'padma' : IDL.Null,
  'skanda' : IDL.Null,
  'kurma' : IDL.Null,
  'vishnu' : IDL.Null,
  'brahmavaivarta' : IDL.Null,
});
export const UpanishadName = IDL.Variant({
  'mundaka' : IDL.Null,
  'aitareya' : IDL.Null,
  'isha' : IDL.Null,
  'kena' : IDL.Null,
  'chandogya' : IDL.Null,
  'taittiriya' : IDL.Null,
  'brihadaranyaka' : IDL.Null,
  'katha' : IDL.Null,
  'shvetashvatara' : IDL.Null,
  'prashna' : IDL.Null,
  'mandukya' : IDL.Null,
});
export const GranthType = IDL.Variant({
  'gita' : IDL.Null,
  'veda' : VedaName,
  'purana' : PuranaName,
  'upanishad' : UpanishadName,
});
export const Granth = IDL.Record({
  'id' : IDL.Text,
  'sanskritName' : IDL.Text,
  'sourceCitation' : IDL.Text,
  'name' : IDL.Text,
  'granthType' : GranthType,
  'description' : IDL.Text,
  'totalChapters' : IDL.Nat,
});
export const GranthChapter = IDL.Record({
  'sanskritName' : IDL.Text,
  'verseCount' : IDL.Nat,
  'name' : IDL.Text,
  'chapterId' : IDL.Nat,
  'summary' : IDL.Text,
  'granthId' : IDL.Text,
});
export const GranthVerse = IDL.Record({
  'sourceGranth' : IDL.Text,
  'sourceChapter' : IDL.Nat,
  'verseNumber' : IDL.Text,
  'sourceVerse' : IDL.Text,
  'chapterId' : IDL.Nat,
  'verseId' : IDL.Nat,
  'sanskritDevanagari' : IDL.Text,
  'simpleMeaning' : IDL.Text,
  'sanskritTransliteration' : IDL.Text,
  'granthId' : IDL.Text,
});
export const GuidanceResult = IDL.Record({
  'guidanceText' : IDL.Text,
  'verse' : IDL.Nat,
  'keyword' : IDL.Text,
  'chapter' : IDL.Nat,
});
export const HeatmapEntry = IDL.Record({
  'allGoalsMet' : IDL.Bool,
  'chaptersRead' : IDL.Nat,
  'date' : IDL.Text,
  'versesRead' : IDL.Nat,
  'principalId' : IDL.Text,
});
export const SiddhiCategory = IDL.Variant({
  'kala' : IDL.Null,
  'mahavidya' : IDL.Null,
  'nidhi' : IDL.Null,
  'siddhi' : IDL.Null,
});
export const SiddhiEntry = IDL.Record({
  'id' : IDL.Text,
  'sourceGranth' : IDL.Text,
  'guruDisclaimer' : IDL.Text,
  'sourceChapter' : IDL.Text,
  'sanskritName' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sourceVerse' : IDL.Text,
  'significance' : IDL.Text,
  'category' : SiddhiCategory,
});
export const KarmaType = IDL.Record({
  'id' : IDL.Text,
  'sourceGranth' : IDL.Text,
  'sourceChapter' : IDL.Text,
  'sanskritName' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sourceVerse' : IDL.Text,
  'practice' : IDL.Text,
});
export const DashaEntry = IDL.Record({
  'durationYears' : IDL.Float64,
  'endDate' : IDL.Int,
  'lord' : IDL.Text,
  'startDate' : IDL.Int,
});
export const PlanetPlacement = IDL.Record({
  'house' : IDL.Nat,
  'planet' : IDL.Text,
  'retrograde' : IDL.Bool,
  'sign' : IDL.Nat,
  'degree' : IDL.Float64,
  'nakshatra' : IDL.Text,
  'nakshatraLord' : IDL.Text,
});
export const KundliData = IDL.Record({
  'navamsaLagnaSign' : IDL.Nat,
  'pratyantarDasha' : DashaEntry,
  'lagnaRashi' : IDL.Text,
  'profileId' : IDL.Principal,
  'rulingPlanetGlyph' : IDL.Text,
  'lagnaSign' : IDL.Nat,
  'calculatedAt' : IDL.Int,
  'planets' : IDL.Vec(PlanetPlacement),
  'rulingPlanet' : IDL.Text,
  'antardasha' : DashaEntry,
  'navamsaPlanets' : IDL.Vec(PlanetPlacement),
  'nextDashas' : IDL.Vec(DashaEntry),
  'mahadasha' : DashaEntry,
});
export const LastRiteStep = IDL.Record({
  'id' : IDL.Text,
  'sourceGranth' : IDL.Text,
  'title' : IDL.Text,
  'sourceChapter' : IDL.Text,
  'sanskritName' : IDL.Text,
  'description' : IDL.Text,
  'sourceVerse' : IDL.Text,
  'stepNumber' : IDL.Nat,
  'mantra' : IDL.Text,
  'procedure' : IDL.Text,
});
export const LeaderboardEntry = IDL.Record({
  'donorName' : IDL.Text,
  'rank' : IDL.Nat,
  'lastDonationAt' : IDL.Int,
  'totalDonation' : IDL.Nat,
  'donorPrincipal' : IDL.Text,
  'donationCount' : IDL.Nat,
});
export const MantraCategory = IDL.Variant({
  'sharanam' : IDL.Null,
  'protection' : IDL.Null,
  'mahamantra' : IDL.Null,
  'general' : IDL.Null,
});
export const MantraEntry = IDL.Record({
  'id' : IDL.Text,
  'meaning' : IDL.Text,
  'name' : IDL.Text,
  'text' : IDL.Text,
  'category' : MantraCategory,
  'benefit' : IDL.Text,
  'recommendedCount' : IDL.Nat,
});
export const MaunaPractice = IDL.Record({
  'id' : IDL.Text,
  'sourceGranth' : IDL.Text,
  'duration' : IDL.Text,
  'sourceChapter' : IDL.Text,
  'sanskritName' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sourceVerse' : IDL.Text,
  'benefits' : IDL.Vec(IDL.Text),
});
export const MokshaTeaching = IDL.Record({
  'id' : IDL.Text,
  'sourceGranth' : IDL.Text,
  'sourceChapter' : IDL.Nat,
  'verse' : IDL.Text,
  'sourceVerse' : IDL.Text,
  'sanskritDevanagari' : IDL.Text,
  'chapter' : IDL.Nat,
  'simpleMeaning' : IDL.Text,
  'commentary' : IDL.Text,
  'sanskritTransliteration' : IDL.Text,
});
export const NaamPledge = IDL.Record({
  'displayName' : IDL.Text,
  'pledgedAt' : IDL.Int,
  'completedCount' : IDL.Nat,
  'isActive' : IDL.Bool,
  'lastUpdatedAt' : IDL.Int,
  'pledgedCount' : IDL.Nat,
  'mantraName' : IDL.Text,
  'principalId' : IDL.Text,
});
export const PanchangData = IDL.Record({
  'tithi' : IDL.Text,
  'date' : IDL.Text,
  'masa' : IDL.Text,
  'ritu' : IDL.Text,
  'vaar' : IDL.Text,
  'yoga' : IDL.Text,
  'moonSign' : IDL.Text,
  'description' : IDL.Text,
  'nakshatra' : IDL.Text,
  'paksha' : IDL.Text,
  'karana' : IDL.Text,
  'tithiNumber' : IDL.Nat,
});
export const PitruRite = IDL.Record({
  'id' : IDL.Text,
  'sourceGranth' : IDL.Text,
  'offerings' : IDL.Vec(IDL.Text),
  'sourceChapter' : IDL.Text,
  'timing' : IDL.Text,
  'sanskritName' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sourceVerse' : IDL.Text,
  'procedure' : IDL.Text,
});
export const PregnancyWeek = IDL.Record({
  'sourceGranth' : IDL.Text,
  'title' : IDL.Text,
  'sourceChapter' : IDL.Text,
  'trimester' : IDL.Nat,
  'sourceVerse' : IDL.Text,
  'weekNumber' : IDL.Nat,
  'saadhna' : IDL.Text,
  'development' : IDL.Text,
  'mantra' : IDL.Text,
  'garbhaSanskarTip' : IDL.Text,
});
export const Badge = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'earnedAt' : IDL.Int,
  'iconGlyph' : IDL.Text,
});
export const PunyaProfile = IDL.Record({
  'currentStreakDays' : IDL.Nat,
  'badges' : IDL.Vec(Badge),
  'totalPoints' : IDL.Nat,
  'longestStreakDays' : IDL.Nat,
  'lastActivityAt' : IDL.Int,
  'principalId' : IDL.Text,
});
export const RemedyReminder = IDL.Record({
  'isActive' : IDL.Bool,
  'reminderTime' : IDL.Text,
  'graha' : IDL.Text,
});
export const RitualExplanation = IDL.Record({
  'id' : IDL.Text,
  'sourceGranth' : IDL.Text,
  'title' : IDL.Text,
  'sourceChapter' : IDL.Text,
  'ritualName' : IDL.Text,
  'explanation' : IDL.Text,
  'sourceVerse' : IDL.Text,
  'relatedDutyIds' : IDL.Vec(IDL.Text),
});
export const Sampradaya = IDL.Record({
  'id' : IDL.Text,
  'sourceGranth' : IDL.Text,
  'sourceChapter' : IDL.Text,
  'lineage' : IDL.Vec(IDL.Text),
  'sanskritName' : IDL.Text,
  'name' : IDL.Text,
  'sourceVerse' : IDL.Text,
  'founder' : IDL.Text,
  'philosophy' : IDL.Text,
});
export const Sanskaar = IDL.Record({
  'id' : IDL.Text,
  'sourceGranth' : IDL.Text,
  'sourceChapter' : IDL.Text,
  'timing' : IDL.Text,
  'sanskritName' : IDL.Text,
  'name' : IDL.Text,
  'sanskaarNumber' : IDL.Nat,
  'description' : IDL.Text,
  'sourceVerse' : IDL.Text,
  'significance' : IDL.Text,
  'mantra' : IDL.Text,
  'procedure' : IDL.Vec(IDL.Text),
});
export const SatsangCircle = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'memberCount' : IDL.Nat,
  'description' : IDL.Text,
  'iconGlyph' : IDL.Text,
});
export const ShauchaPractice = IDL.Record({
  'id' : IDL.Text,
  'sourceGranth' : IDL.Text,
  'sourceChapter' : IDL.Text,
  'sanskritName' : IDL.Text,
  'kind' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sourceVerse' : IDL.Text,
  'practice' : IDL.Text,
  'benefits' : IDL.Vec(IDL.Text),
});
export const TarotCard = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'suit' : IDL.Text,
  'reversedMeaning' : IDL.Text,
  'number' : IDL.Nat,
  'uprightMeaning' : IDL.Text,
  'arcana' : IDL.Text,
  'imagery' : IDL.Text,
  'symbolism' : IDL.Text,
});
export const TransitEvent = IDL.Record({
  'remedy' : IDL.Text,
  'colorCode' : IDL.Text,
  'endDate' : IDL.Text,
  'planet' : IDL.Text,
  'description' : IDL.Text,
  'startDate' : IDL.Text,
  'eventType' : IDL.Text,
});
export const DateOfBirth = IDL.Record({
  'day' : IDL.Nat,
  'month' : IDL.Nat,
  'year' : IDL.Nat,
});
export const TimeOfBirth = IDL.Record({ 'hour' : IDL.Nat, 'minute' : IDL.Nat });
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'placeOfBirth' : IDL.Text,
  'latitude' : IDL.Float64,
  'timezone' : IDL.Text,
  'dateOfBirth' : DateOfBirth,
  'newsletterOptIn' : IDL.Bool,
  'createdAt' : IDL.Int,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'updatedAt' : IDL.Int,
  'timeOfBirth' : TimeOfBirth,
  'longitude' : IDL.Float64,
  'phone' : IDL.Text,
});
export const Verse = IDL.Record({
  'id' : IDL.Nat,
  'verseNumber' : IDL.Text,
  'sanskritText' : IDL.Text,
  'chapterId' : IDL.Nat,
  'transliteration' : IDL.Text,
  'englishTranslation' : IDL.Text,
});
export const VerseCommentary = IDL.Record({
  'tilak' : IDL.Text,
  'shankaracharya' : IDL.Text,
  'verseId' : IDL.Text,
  'ramanuja' : IDL.Text,
});
export const WorshipStep = IDL.Record({
  'id' : IDL.Text,
  'sourceGranth' : IDL.Text,
  'sourceChapter' : IDL.Text,
  'sanskritName' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sourceVerse' : IDL.Text,
  'stepNumber' : IDL.Nat,
  'mantra' : IDL.Text,
  'procedure' : IDL.Text,
});
export const YugCycle = IDL.Record({
  'id' : IDL.Text,
  'sourceGranth' : IDL.Text,
  'durationYears' : IDL.Nat,
  'sourceChapter' : IDL.Text,
  'sanskritName' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'sourceVerse' : IDL.Text,
  'characteristics' : IDL.Text,
  'dharmaQuarter' : IDL.Nat,
});
export const EmailSubscriber = IDL.Record({
  'active' : IDL.Bool,
  'subscribedAt' : IDL.Int,
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const UserProfileInput = IDL.Record({
  'placeOfBirth' : IDL.Text,
  'latitude' : IDL.Float64,
  'timezone' : IDL.Text,
  'dateOfBirth' : DateOfBirth,
  'newsletterOptIn' : IDL.Bool,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'timeOfBirth' : TimeOfBirth,
  'longitude' : IDL.Float64,
  'phone' : IDL.Text,
});
export const DonationInfoInput = IDL.Record({
  'qrCodeAssetId' : IDL.Text,
  'ifscCode' : IDL.Text,
  'bankName' : IDL.Text,
  'accountName' : IDL.Text,
  'upiId' : IDL.Text,
  'accountNumber' : IDL.Text,
});
export const AdminConfigInput = IDL.Record({
  'newsletterEnabled' : IDL.Bool,
  'appVersion' : IDL.Text,
  'senderName' : IDL.Text,
  'senderEmail' : IDL.Text,
});
export const GalleryImageInput = IDL.Record({
  'asset' : ExternalBlob,
  'caption' : IDL.Text,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'adminListAllGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImageMeta)], []),
  'clearOldMessages' : IDL.Func([], [], []),
  'createJournalEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [JournalEntry],
      [],
    ),
  'deleteJournalEntry' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'drawTarot' : IDL.Func([IDL.Text, IDL.Text], [TarotReading], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getAdminConfig' : IDL.Func([], [AdminConfig], ['query']),
  'getAllGrahaRemedies' : IDL.Func([], [IDL.Vec(GrahaRemedyData)], ['query']),
  'getChapter' : IDL.Func([IDL.Nat], [IDL.Opt(Chapter)], ['query']),
  'getCircleMessages' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SatsangMessage)],
      ['query'],
    ),
  'getConcentrationHistory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ConcentrationSession)],
      ['query'],
    ),
  'getDailyChallenge' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DailyChallenge)],
      ['query'],
    ),
  'getDailyDuty' : IDL.Func([IDL.Text], [IDL.Opt(DailyDuty)], ['query']),
  'getDailyQuiz' : IDL.Func([IDL.Text], [IDL.Opt(QuizQuestion)], ['query']),
  'getDevlokStage' : IDL.Func([IDL.Text], [IDL.Opt(DevlokStage)], ['query']),
  'getDharmaBodhStep' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DharmaBodhStep)],
      ['query'],
    ),
  'getDharmaPillar' : IDL.Func([IDL.Text], [IDL.Opt(DharmaPillar)], ['query']),
  'getDikshaVidhi' : IDL.Func([IDL.Text], [IDL.Opt(DikshaVidhi)], ['query']),
  'getDonationInfo' : IDL.Func([], [IDL.Opt(DonationInfo)], ['query']),
  'getFestivals' : IDL.Func([], [IDL.Vec(Festival)], ['query']),
  'getGalleryUploads' : IDL.Func([], [IDL.Vec(GalleryImageMeta)], ['query']),
  'getGrahaRemedy' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(GrahaRemedyData)],
      ['query'],
    ),
  'getGranth' : IDL.Func([IDL.Text], [IDL.Opt(Granth)], ['query']),
  'getGranthChapter' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Opt(GranthChapter)],
      ['query'],
    ),
  'getGranthVerse' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Opt(GranthVerse)],
      ['query'],
    ),
  'getGuidanceByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(GuidanceResult)],
      ['query'],
    ),
  'getHeatmapData' : IDL.Func([IDL.Nat], [IDL.Vec(HeatmapEntry)], ['query']),
  'getJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
  'getKala' : IDL.Func([IDL.Text], [IDL.Opt(SiddhiEntry)], ['query']),
  'getKarmaType' : IDL.Func([IDL.Text], [IDL.Opt(KarmaType)], ['query']),
  'getKrishnaGuidance' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(GuidanceResult)],
      ['query'],
    ),
  'getKundliData' : IDL.Func([], [IDL.Opt(KundliData)], ['query']),
  'getLastRiteStep' : IDL.Func([IDL.Text], [IDL.Opt(LastRiteStep)], ['query']),
  'getLeaderboard' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(LeaderboardEntry)],
      ['query'],
    ),
  'getMahavidya' : IDL.Func([IDL.Text], [IDL.Opt(SiddhiEntry)], ['query']),
  'getMantras' : IDL.Func([], [IDL.Vec(MantraEntry)], ['query']),
  'getMaunaPractice' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(MaunaPractice)],
      ['query'],
    ),
  'getMokshaTeaching' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(MokshaTeaching)],
      ['query'],
    ),
  'getNaamPledges' : IDL.Func([], [IDL.Vec(NaamPledge)], ['query']),
  'getNidhi' : IDL.Func([IDL.Text], [IDL.Opt(SiddhiEntry)], ['query']),
  'getPanchaang' : IDL.Func([IDL.Text], [PanchangData], ['query']),
  'getPanchangToday' : IDL.Func([IDL.Text], [PanchangData], ['query']),
  'getPitruRite' : IDL.Func([IDL.Text], [IDL.Opt(PitruRite)], ['query']),
  'getPregnancyWeek' : IDL.Func([IDL.Nat], [IDL.Opt(PregnancyWeek)], ['query']),
  'getPunyaProfile' : IDL.Func([], [IDL.Opt(PunyaProfile)], []),
  'getReadingStreak' : IDL.Func([], [IDL.Nat], ['query']),
  'getRemedyReminder' : IDL.Func([], [IDL.Opt(RemedyReminder)], ['query']),
  'getRitualExplanation' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(RitualExplanation)],
      ['query'],
    ),
  'getSampradaya' : IDL.Func([IDL.Text], [IDL.Opt(Sampradaya)], ['query']),
  'getSanskaar' : IDL.Func([IDL.Text], [IDL.Opt(Sanskaar)], ['query']),
  'getSatsangCircle' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(SatsangCircle)],
      ['query'],
    ),
  'getShauchaPractice' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(ShauchaPractice)],
      ['query'],
    ),
  'getSiddhi' : IDL.Func([IDL.Text], [IDL.Opt(SiddhiEntry)], ['query']),
  'getTarotCard' : IDL.Func([IDL.Text], [IDL.Opt(TarotCard)], ['query']),
  'getTransitCalendar' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(TransitEvent)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getVerse' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Opt(Verse)], ['query']),
  'getVerseCommentary' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(VerseCommentary)],
      ['query'],
    ),
  'getWorshipStep' : IDL.Func([IDL.Text], [IDL.Opt(WorshipStep)], ['query']),
  'getYugCycle' : IDL.Func([IDL.Text], [IDL.Opt(YugCycle)], ['query']),
  'listChapters' : IDL.Func([], [IDL.Vec(Chapter)], ['query']),
  'listDailyDuties' : IDL.Func([], [IDL.Vec(DailyDuty)], ['query']),
  'listDevlokStages' : IDL.Func([], [IDL.Vec(DevlokStage)], ['query']),
  'listDharmaBodhSteps' : IDL.Func([], [IDL.Vec(DharmaBodhStep)], ['query']),
  'listDharmaPillars' : IDL.Func([], [IDL.Vec(DharmaPillar)], ['query']),
  'listGranthChapters' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(GranthChapter)],
      ['query'],
    ),
  'listGranthVerses' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Vec(GranthVerse)],
      ['query'],
    ),
  'listGranths' : IDL.Func([], [IDL.Vec(Granth)], ['query']),
  'listKalas' : IDL.Func([], [IDL.Vec(SiddhiEntry)], ['query']),
  'listKarmaTypes' : IDL.Func([], [IDL.Vec(KarmaType)], ['query']),
  'listLastRiteSteps' : IDL.Func([], [IDL.Vec(LastRiteStep)], ['query']),
  'listMahavidyas' : IDL.Func([], [IDL.Vec(SiddhiEntry)], ['query']),
  'listMaunaPractices' : IDL.Func([], [IDL.Vec(MaunaPractice)], ['query']),
  'listMokshaTeachings' : IDL.Func([], [IDL.Vec(MokshaTeaching)], ['query']),
  'listNewsletterSubscribers' : IDL.Func([], [IDL.Vec(EmailSubscriber)], []),
  'listNidhis' : IDL.Func([], [IDL.Vec(SiddhiEntry)], ['query']),
  'listPitruRites' : IDL.Func([], [IDL.Vec(PitruRite)], ['query']),
  'listPregnancyWeeks' : IDL.Func([], [IDL.Vec(PregnancyWeek)], ['query']),
  'listRitualExplanations' : IDL.Func(
      [],
      [IDL.Vec(RitualExplanation)],
      ['query'],
    ),
  'listSampradayas' : IDL.Func([], [IDL.Vec(Sampradaya)], ['query']),
  'listSanskaars' : IDL.Func([], [IDL.Vec(Sanskaar)], ['query']),
  'listSatsangCircleMetadata' : IDL.Func(
      [],
      [IDL.Vec(SatsangCircle)],
      ['query'],
    ),
  'listSatsangCircles' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'listShauchaPractices' : IDL.Func([], [IDL.Vec(ShauchaPractice)], ['query']),
  'listSiddhis' : IDL.Func([], [IDL.Vec(SiddhiEntry)], ['query']),
  'listTarotCards' : IDL.Func([], [IDL.Vec(TarotCard)], ['query']),
  'listVerses' : IDL.Func([IDL.Nat], [IDL.Vec(Verse)], ['query']),
  'listWorshipSteps' : IDL.Func([], [IDL.Vec(WorshipStep)], ['query']),
  'listYugCycles' : IDL.Func([], [IDL.Vec(YugCycle)], ['query']),
  'postCircleMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'recordConcentrationSession' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [ConcentrationSession],
      [],
    ),
  'recordDailyReading' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Bool],
      [HeatmapEntry],
      [],
    ),
  'saveKundliData' : IDL.Func([KundliData], [IDL.Bool], []),
  'saveRemedyReminder' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'saveUserProfile' : IDL.Func([UserProfileInput], [IDL.Bool], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'searchJournalEntries' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(JournalEntry)],
      ['query'],
    ),
  'setDonationInfo' : IDL.Func([DonationInfoInput], [IDL.Bool], []),
  'setGalleryImageApproval' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
  'subscribeNewsletter' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'unsubscribeNewsletter' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'updateAdminConfig' : IDL.Func([AdminConfigInput], [IDL.Bool], []),
  'updateJournalEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Opt(JournalEntry)],
      [],
    ),
  'uploadGalleryImage' : IDL.Func([GalleryImageInput], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const GalleryImageMeta = IDL.Record({
    'id' : IDL.Nat,
    'isApproved' : IDL.Bool,
    'asset' : ExternalBlob,
    'caption' : IDL.Text,
    'category' : IDL.Text,
    'uploader' : IDL.Principal,
    'uploadedAt' : IDL.Int,
  });
  const JournalEntry = IDL.Record({
    'id' : IDL.Text,
    'mood' : IDL.Text,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'verseId' : IDL.Text,
    'updatedAt' : IDL.Int,
    'principalId' : IDL.Text,
  });
  const TarotDraw = IDL.Record({
    'positionName' : IDL.Text,
    'cardId' : IDL.Text,
    'position' : IDL.Nat,
    'isReversed' : IDL.Bool,
  });
  const TarotReading = IDL.Record({
    'id' : IDL.Text,
    'spreadType' : IDL.Text,
    'question' : IDL.Text,
    'interpretation' : IDL.Text,
    'guidance' : IDL.Text,
    'draws' : IDL.Vec(TarotDraw),
    'principalId' : IDL.Text,
    'readAt' : IDL.Int,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const AdminConfig = IDL.Record({
    'newsletterEnabled' : IDL.Bool,
    'appVersion' : IDL.Text,
    'senderName' : IDL.Text,
    'senderEmail' : IDL.Text,
  });
  const GrahaRemedyData = IDL.Record({
    'avoidList' : IDL.Vec(IDL.Text),
    'daan' : IDL.Text,
    'role' : IDL.Text,
    'mantraSanskrit' : IDL.Text,
    'mantraCount' : IDL.Nat,
    'gemstone' : IDL.Text,
    'graha' : IDL.Text,
    'weakCauses' : IDL.Vec(IDL.Text),
    'gemstoneWarning' : IDL.Text,
    'remedies' : IDL.Vec(IDL.Text),
    'strongGives' : IDL.Vec(IDL.Text),
  });
  const Chapter = IDL.Record({
    'id' : IDL.Nat,
    'verseCount' : IDL.Nat,
    'name' : IDL.Text,
    'summary' : IDL.Text,
  });
  const SatsangMessage = IDL.Record({
    'circleId' : IDL.Text,
    'authorName' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const ConcentrationSession = IDL.Record({
    'id' : IDL.Text,
    'completedAt' : IDL.Int,
    'sessionType' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'principalId' : IDL.Text,
  });
  const DailyChallenge = IDL.Record({
    'action' : IDL.Text,
    'date' : IDL.Text,
    'task' : IDL.Text,
    'points' : IDL.Nat,
  });
  const DailyDuty = IDL.Record({
    'id' : IDL.Text,
    'sourceGranth' : IDL.Text,
    'sourceChapter' : IDL.Text,
    'timing' : IDL.Text,
    'sanskritName' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sourceVerse' : IDL.Text,
    'linkedExplanationId' : IDL.Text,
    'practice' : IDL.Text,
    'category' : IDL.Text,
  });
  const QuizQuestion = IDL.Record({
    'id' : IDL.Text,
    'sourceGranth' : IDL.Text,
    'question' : IDL.Text,
    'correctIndex' : IDL.Nat,
    'date' : IDL.Text,
    'explanation' : IDL.Text,
    'sourceVerse' : IDL.Text,
    'options' : IDL.Vec(IDL.Text),
    'points' : IDL.Nat,
  });
  const DevlokStage = IDL.Record({
    'id' : IDL.Text,
    'sourceGranth' : IDL.Text,
    'sourceChapter' : IDL.Text,
    'sanskritName' : IDL.Text,
    'stageNumber' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sourceVerse' : IDL.Text,
    'significance' : IDL.Text,
  });
  const DharmaBodhStep = IDL.Record({
    'id' : IDL.Text,
    'sourceGranth' : IDL.Text,
    'title' : IDL.Text,
    'sourceChapter' : IDL.Text,
    'sanskritName' : IDL.Text,
    'question' : IDL.Text,
    'sourceVerse' : IDL.Text,
    'stepNumber' : IDL.Nat,
    'practice' : IDL.Text,
    'guidance' : IDL.Text,
  });
  const DharmaPillar = IDL.Record({
    'id' : IDL.Text,
    'sourceGranth' : IDL.Text,
    'sourceChapter' : IDL.Text,
    'sanskritName' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sourceVerse' : IDL.Text,
    'practice' : IDL.Text,
  });
  const DikshaVidhi = IDL.Record({
    'id' : IDL.Text,
    'sourceGranth' : IDL.Text,
    'sourceChapter' : IDL.Text,
    'sanskritName' : IDL.Text,
    'prerequisites' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sourceVerse' : IDL.Text,
    'mantra' : IDL.Text,
    'procedure' : IDL.Vec(IDL.Text),
  });
  const DonationInfo = IDL.Record({
    'qrCodeAssetId' : IDL.Text,
    'ifscCode' : IDL.Text,
    'bankName' : IDL.Text,
    'updatedAt' : IDL.Int,
    'accountName' : IDL.Text,
    'upiId' : IDL.Text,
    'accountNumber' : IDL.Text,
  });
  const Festival = IDL.Record({
    'sourceGranth' : IDL.Text,
    'dateStr' : IDL.Text,
    'sourceChapter' : IDL.Text,
    'meaning' : IDL.Text,
    'name' : IDL.Text,
    'sourceVerse' : IDL.Text,
    'story' : IDL.Text,
    'mantraName' : IDL.Text,
    'recommendedVerse' : IDL.Text,
  });
  const VedaName = IDL.Variant({
    'rig' : IDL.Null,
    'atharva' : IDL.Null,
    'sama' : IDL.Null,
    'yajur' : IDL.Null,
  });
  const PuranaName = IDL.Variant({
    'markandeya' : IDL.Null,
    'brahma' : IDL.Null,
    'bhagavata' : IDL.Null,
    'narada' : IDL.Null,
    'agni' : IDL.Null,
    'vamana' : IDL.Null,
    'varaha' : IDL.Null,
    'garuda' : IDL.Null,
    'linga' : IDL.Null,
    'shiva' : IDL.Null,
    'brahmanda' : IDL.Null,
    'bhavishya' : IDL.Null,
    'matsya' : IDL.Null,
    'padma' : IDL.Null,
    'skanda' : IDL.Null,
    'kurma' : IDL.Null,
    'vishnu' : IDL.Null,
    'brahmavaivarta' : IDL.Null,
  });
  const UpanishadName = IDL.Variant({
    'mundaka' : IDL.Null,
    'aitareya' : IDL.Null,
    'isha' : IDL.Null,
    'kena' : IDL.Null,
    'chandogya' : IDL.Null,
    'taittiriya' : IDL.Null,
    'brihadaranyaka' : IDL.Null,
    'katha' : IDL.Null,
    'shvetashvatara' : IDL.Null,
    'prashna' : IDL.Null,
    'mandukya' : IDL.Null,
  });
  const GranthType = IDL.Variant({
    'gita' : IDL.Null,
    'veda' : VedaName,
    'purana' : PuranaName,
    'upanishad' : UpanishadName,
  });
  const Granth = IDL.Record({
    'id' : IDL.Text,
    'sanskritName' : IDL.Text,
    'sourceCitation' : IDL.Text,
    'name' : IDL.Text,
    'granthType' : GranthType,
    'description' : IDL.Text,
    'totalChapters' : IDL.Nat,
  });
  const GranthChapter = IDL.Record({
    'sanskritName' : IDL.Text,
    'verseCount' : IDL.Nat,
    'name' : IDL.Text,
    'chapterId' : IDL.Nat,
    'summary' : IDL.Text,
    'granthId' : IDL.Text,
  });
  const GranthVerse = IDL.Record({
    'sourceGranth' : IDL.Text,
    'sourceChapter' : IDL.Nat,
    'verseNumber' : IDL.Text,
    'sourceVerse' : IDL.Text,
    'chapterId' : IDL.Nat,
    'verseId' : IDL.Nat,
    'sanskritDevanagari' : IDL.Text,
    'simpleMeaning' : IDL.Text,
    'sanskritTransliteration' : IDL.Text,
    'granthId' : IDL.Text,
  });
  const GuidanceResult = IDL.Record({
    'guidanceText' : IDL.Text,
    'verse' : IDL.Nat,
    'keyword' : IDL.Text,
    'chapter' : IDL.Nat,
  });
  const HeatmapEntry = IDL.Record({
    'allGoalsMet' : IDL.Bool,
    'chaptersRead' : IDL.Nat,
    'date' : IDL.Text,
    'versesRead' : IDL.Nat,
    'principalId' : IDL.Text,
  });
  const SiddhiCategory = IDL.Variant({
    'kala' : IDL.Null,
    'mahavidya' : IDL.Null,
    'nidhi' : IDL.Null,
    'siddhi' : IDL.Null,
  });
  const SiddhiEntry = IDL.Record({
    'id' : IDL.Text,
    'sourceGranth' : IDL.Text,
    'guruDisclaimer' : IDL.Text,
    'sourceChapter' : IDL.Text,
    'sanskritName' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sourceVerse' : IDL.Text,
    'significance' : IDL.Text,
    'category' : SiddhiCategory,
  });
  const KarmaType = IDL.Record({
    'id' : IDL.Text,
    'sourceGranth' : IDL.Text,
    'sourceChapter' : IDL.Text,
    'sanskritName' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sourceVerse' : IDL.Text,
    'practice' : IDL.Text,
  });
  const DashaEntry = IDL.Record({
    'durationYears' : IDL.Float64,
    'endDate' : IDL.Int,
    'lord' : IDL.Text,
    'startDate' : IDL.Int,
  });
  const PlanetPlacement = IDL.Record({
    'house' : IDL.Nat,
    'planet' : IDL.Text,
    'retrograde' : IDL.Bool,
    'sign' : IDL.Nat,
    'degree' : IDL.Float64,
    'nakshatra' : IDL.Text,
    'nakshatraLord' : IDL.Text,
  });
  const KundliData = IDL.Record({
    'navamsaLagnaSign' : IDL.Nat,
    'pratyantarDasha' : DashaEntry,
    'lagnaRashi' : IDL.Text,
    'profileId' : IDL.Principal,
    'rulingPlanetGlyph' : IDL.Text,
    'lagnaSign' : IDL.Nat,
    'calculatedAt' : IDL.Int,
    'planets' : IDL.Vec(PlanetPlacement),
    'rulingPlanet' : IDL.Text,
    'antardasha' : DashaEntry,
    'navamsaPlanets' : IDL.Vec(PlanetPlacement),
    'nextDashas' : IDL.Vec(DashaEntry),
    'mahadasha' : DashaEntry,
  });
  const LastRiteStep = IDL.Record({
    'id' : IDL.Text,
    'sourceGranth' : IDL.Text,
    'title' : IDL.Text,
    'sourceChapter' : IDL.Text,
    'sanskritName' : IDL.Text,
    'description' : IDL.Text,
    'sourceVerse' : IDL.Text,
    'stepNumber' : IDL.Nat,
    'mantra' : IDL.Text,
    'procedure' : IDL.Text,
  });
  const LeaderboardEntry = IDL.Record({
    'donorName' : IDL.Text,
    'rank' : IDL.Nat,
    'lastDonationAt' : IDL.Int,
    'totalDonation' : IDL.Nat,
    'donorPrincipal' : IDL.Text,
    'donationCount' : IDL.Nat,
  });
  const MantraCategory = IDL.Variant({
    'sharanam' : IDL.Null,
    'protection' : IDL.Null,
    'mahamantra' : IDL.Null,
    'general' : IDL.Null,
  });
  const MantraEntry = IDL.Record({
    'id' : IDL.Text,
    'meaning' : IDL.Text,
    'name' : IDL.Text,
    'text' : IDL.Text,
    'category' : MantraCategory,
    'benefit' : IDL.Text,
    'recommendedCount' : IDL.Nat,
  });
  const MaunaPractice = IDL.Record({
    'id' : IDL.Text,
    'sourceGranth' : IDL.Text,
    'duration' : IDL.Text,
    'sourceChapter' : IDL.Text,
    'sanskritName' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sourceVerse' : IDL.Text,
    'benefits' : IDL.Vec(IDL.Text),
  });
  const MokshaTeaching = IDL.Record({
    'id' : IDL.Text,
    'sourceGranth' : IDL.Text,
    'sourceChapter' : IDL.Nat,
    'verse' : IDL.Text,
    'sourceVerse' : IDL.Text,
    'sanskritDevanagari' : IDL.Text,
    'chapter' : IDL.Nat,
    'simpleMeaning' : IDL.Text,
    'commentary' : IDL.Text,
    'sanskritTransliteration' : IDL.Text,
  });
  const NaamPledge = IDL.Record({
    'displayName' : IDL.Text,
    'pledgedAt' : IDL.Int,
    'completedCount' : IDL.Nat,
    'isActive' : IDL.Bool,
    'lastUpdatedAt' : IDL.Int,
    'pledgedCount' : IDL.Nat,
    'mantraName' : IDL.Text,
    'principalId' : IDL.Text,
  });
  const PanchangData = IDL.Record({
    'tithi' : IDL.Text,
    'date' : IDL.Text,
    'masa' : IDL.Text,
    'ritu' : IDL.Text,
    'vaar' : IDL.Text,
    'yoga' : IDL.Text,
    'moonSign' : IDL.Text,
    'description' : IDL.Text,
    'nakshatra' : IDL.Text,
    'paksha' : IDL.Text,
    'karana' : IDL.Text,
    'tithiNumber' : IDL.Nat,
  });
  const PitruRite = IDL.Record({
    'id' : IDL.Text,
    'sourceGranth' : IDL.Text,
    'offerings' : IDL.Vec(IDL.Text),
    'sourceChapter' : IDL.Text,
    'timing' : IDL.Text,
    'sanskritName' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sourceVerse' : IDL.Text,
    'procedure' : IDL.Text,
  });
  const PregnancyWeek = IDL.Record({
    'sourceGranth' : IDL.Text,
    'title' : IDL.Text,
    'sourceChapter' : IDL.Text,
    'trimester' : IDL.Nat,
    'sourceVerse' : IDL.Text,
    'weekNumber' : IDL.Nat,
    'saadhna' : IDL.Text,
    'development' : IDL.Text,
    'mantra' : IDL.Text,
    'garbhaSanskarTip' : IDL.Text,
  });
  const Badge = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'earnedAt' : IDL.Int,
    'iconGlyph' : IDL.Text,
  });
  const PunyaProfile = IDL.Record({
    'currentStreakDays' : IDL.Nat,
    'badges' : IDL.Vec(Badge),
    'totalPoints' : IDL.Nat,
    'longestStreakDays' : IDL.Nat,
    'lastActivityAt' : IDL.Int,
    'principalId' : IDL.Text,
  });
  const RemedyReminder = IDL.Record({
    'isActive' : IDL.Bool,
    'reminderTime' : IDL.Text,
    'graha' : IDL.Text,
  });
  const RitualExplanation = IDL.Record({
    'id' : IDL.Text,
    'sourceGranth' : IDL.Text,
    'title' : IDL.Text,
    'sourceChapter' : IDL.Text,
    'ritualName' : IDL.Text,
    'explanation' : IDL.Text,
    'sourceVerse' : IDL.Text,
    'relatedDutyIds' : IDL.Vec(IDL.Text),
  });
  const Sampradaya = IDL.Record({
    'id' : IDL.Text,
    'sourceGranth' : IDL.Text,
    'sourceChapter' : IDL.Text,
    'lineage' : IDL.Vec(IDL.Text),
    'sanskritName' : IDL.Text,
    'name' : IDL.Text,
    'sourceVerse' : IDL.Text,
    'founder' : IDL.Text,
    'philosophy' : IDL.Text,
  });
  const Sanskaar = IDL.Record({
    'id' : IDL.Text,
    'sourceGranth' : IDL.Text,
    'sourceChapter' : IDL.Text,
    'timing' : IDL.Text,
    'sanskritName' : IDL.Text,
    'name' : IDL.Text,
    'sanskaarNumber' : IDL.Nat,
    'description' : IDL.Text,
    'sourceVerse' : IDL.Text,
    'significance' : IDL.Text,
    'mantra' : IDL.Text,
    'procedure' : IDL.Vec(IDL.Text),
  });
  const SatsangCircle = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'memberCount' : IDL.Nat,
    'description' : IDL.Text,
    'iconGlyph' : IDL.Text,
  });
  const ShauchaPractice = IDL.Record({
    'id' : IDL.Text,
    'sourceGranth' : IDL.Text,
    'sourceChapter' : IDL.Text,
    'sanskritName' : IDL.Text,
    'kind' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sourceVerse' : IDL.Text,
    'practice' : IDL.Text,
    'benefits' : IDL.Vec(IDL.Text),
  });
  const TarotCard = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'suit' : IDL.Text,
    'reversedMeaning' : IDL.Text,
    'number' : IDL.Nat,
    'uprightMeaning' : IDL.Text,
    'arcana' : IDL.Text,
    'imagery' : IDL.Text,
    'symbolism' : IDL.Text,
  });
  const TransitEvent = IDL.Record({
    'remedy' : IDL.Text,
    'colorCode' : IDL.Text,
    'endDate' : IDL.Text,
    'planet' : IDL.Text,
    'description' : IDL.Text,
    'startDate' : IDL.Text,
    'eventType' : IDL.Text,
  });
  const DateOfBirth = IDL.Record({
    'day' : IDL.Nat,
    'month' : IDL.Nat,
    'year' : IDL.Nat,
  });
  const TimeOfBirth = IDL.Record({ 'hour' : IDL.Nat, 'minute' : IDL.Nat });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'placeOfBirth' : IDL.Text,
    'latitude' : IDL.Float64,
    'timezone' : IDL.Text,
    'dateOfBirth' : DateOfBirth,
    'newsletterOptIn' : IDL.Bool,
    'createdAt' : IDL.Int,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'updatedAt' : IDL.Int,
    'timeOfBirth' : TimeOfBirth,
    'longitude' : IDL.Float64,
    'phone' : IDL.Text,
  });
  const Verse = IDL.Record({
    'id' : IDL.Nat,
    'verseNumber' : IDL.Text,
    'sanskritText' : IDL.Text,
    'chapterId' : IDL.Nat,
    'transliteration' : IDL.Text,
    'englishTranslation' : IDL.Text,
  });
  const VerseCommentary = IDL.Record({
    'tilak' : IDL.Text,
    'shankaracharya' : IDL.Text,
    'verseId' : IDL.Text,
    'ramanuja' : IDL.Text,
  });
  const WorshipStep = IDL.Record({
    'id' : IDL.Text,
    'sourceGranth' : IDL.Text,
    'sourceChapter' : IDL.Text,
    'sanskritName' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sourceVerse' : IDL.Text,
    'stepNumber' : IDL.Nat,
    'mantra' : IDL.Text,
    'procedure' : IDL.Text,
  });
  const YugCycle = IDL.Record({
    'id' : IDL.Text,
    'sourceGranth' : IDL.Text,
    'durationYears' : IDL.Nat,
    'sourceChapter' : IDL.Text,
    'sanskritName' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'sourceVerse' : IDL.Text,
    'characteristics' : IDL.Text,
    'dharmaQuarter' : IDL.Nat,
  });
  const EmailSubscriber = IDL.Record({
    'active' : IDL.Bool,
    'subscribedAt' : IDL.Int,
    'name' : IDL.Text,
    'email' : IDL.Text,
  });
  const UserProfileInput = IDL.Record({
    'placeOfBirth' : IDL.Text,
    'latitude' : IDL.Float64,
    'timezone' : IDL.Text,
    'dateOfBirth' : DateOfBirth,
    'newsletterOptIn' : IDL.Bool,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'timeOfBirth' : TimeOfBirth,
    'longitude' : IDL.Float64,
    'phone' : IDL.Text,
  });
  const DonationInfoInput = IDL.Record({
    'qrCodeAssetId' : IDL.Text,
    'ifscCode' : IDL.Text,
    'bankName' : IDL.Text,
    'accountName' : IDL.Text,
    'upiId' : IDL.Text,
    'accountNumber' : IDL.Text,
  });
  const AdminConfigInput = IDL.Record({
    'newsletterEnabled' : IDL.Bool,
    'appVersion' : IDL.Text,
    'senderName' : IDL.Text,
    'senderEmail' : IDL.Text,
  });
  const GalleryImageInput = IDL.Record({
    'asset' : ExternalBlob,
    'caption' : IDL.Text,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'adminListAllGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImageMeta)], []),
    'clearOldMessages' : IDL.Func([], [], []),
    'createJournalEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [JournalEntry],
        [],
      ),
    'deleteJournalEntry' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'drawTarot' : IDL.Func([IDL.Text, IDL.Text], [TarotReading], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getAdminConfig' : IDL.Func([], [AdminConfig], ['query']),
    'getAllGrahaRemedies' : IDL.Func([], [IDL.Vec(GrahaRemedyData)], ['query']),
    'getChapter' : IDL.Func([IDL.Nat], [IDL.Opt(Chapter)], ['query']),
    'getCircleMessages' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SatsangMessage)],
        ['query'],
      ),
    'getConcentrationHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ConcentrationSession)],
        ['query'],
      ),
    'getDailyChallenge' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DailyChallenge)],
        ['query'],
      ),
    'getDailyDuty' : IDL.Func([IDL.Text], [IDL.Opt(DailyDuty)], ['query']),
    'getDailyQuiz' : IDL.Func([IDL.Text], [IDL.Opt(QuizQuestion)], ['query']),
    'getDevlokStage' : IDL.Func([IDL.Text], [IDL.Opt(DevlokStage)], ['query']),
    'getDharmaBodhStep' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DharmaBodhStep)],
        ['query'],
      ),
    'getDharmaPillar' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DharmaPillar)],
        ['query'],
      ),
    'getDikshaVidhi' : IDL.Func([IDL.Text], [IDL.Opt(DikshaVidhi)], ['query']),
    'getDonationInfo' : IDL.Func([], [IDL.Opt(DonationInfo)], ['query']),
    'getFestivals' : IDL.Func([], [IDL.Vec(Festival)], ['query']),
    'getGalleryUploads' : IDL.Func([], [IDL.Vec(GalleryImageMeta)], ['query']),
    'getGrahaRemedy' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(GrahaRemedyData)],
        ['query'],
      ),
    'getGranth' : IDL.Func([IDL.Text], [IDL.Opt(Granth)], ['query']),
    'getGranthChapter' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Opt(GranthChapter)],
        ['query'],
      ),
    'getGranthVerse' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Opt(GranthVerse)],
        ['query'],
      ),
    'getGuidanceByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(GuidanceResult)],
        ['query'],
      ),
    'getHeatmapData' : IDL.Func([IDL.Nat], [IDL.Vec(HeatmapEntry)], ['query']),
    'getJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
    'getKala' : IDL.Func([IDL.Text], [IDL.Opt(SiddhiEntry)], ['query']),
    'getKarmaType' : IDL.Func([IDL.Text], [IDL.Opt(KarmaType)], ['query']),
    'getKrishnaGuidance' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(GuidanceResult)],
        ['query'],
      ),
    'getKundliData' : IDL.Func([], [IDL.Opt(KundliData)], ['query']),
    'getLastRiteStep' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(LastRiteStep)],
        ['query'],
      ),
    'getLeaderboard' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(LeaderboardEntry)],
        ['query'],
      ),
    'getMahavidya' : IDL.Func([IDL.Text], [IDL.Opt(SiddhiEntry)], ['query']),
    'getMantras' : IDL.Func([], [IDL.Vec(MantraEntry)], ['query']),
    'getMaunaPractice' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(MaunaPractice)],
        ['query'],
      ),
    'getMokshaTeaching' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(MokshaTeaching)],
        ['query'],
      ),
    'getNaamPledges' : IDL.Func([], [IDL.Vec(NaamPledge)], ['query']),
    'getNidhi' : IDL.Func([IDL.Text], [IDL.Opt(SiddhiEntry)], ['query']),
    'getPanchaang' : IDL.Func([IDL.Text], [PanchangData], ['query']),
    'getPanchangToday' : IDL.Func([IDL.Text], [PanchangData], ['query']),
    'getPitruRite' : IDL.Func([IDL.Text], [IDL.Opt(PitruRite)], ['query']),
    'getPregnancyWeek' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(PregnancyWeek)],
        ['query'],
      ),
    'getPunyaProfile' : IDL.Func([], [IDL.Opt(PunyaProfile)], []),
    'getReadingStreak' : IDL.Func([], [IDL.Nat], ['query']),
    'getRemedyReminder' : IDL.Func([], [IDL.Opt(RemedyReminder)], ['query']),
    'getRitualExplanation' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(RitualExplanation)],
        ['query'],
      ),
    'getSampradaya' : IDL.Func([IDL.Text], [IDL.Opt(Sampradaya)], ['query']),
    'getSanskaar' : IDL.Func([IDL.Text], [IDL.Opt(Sanskaar)], ['query']),
    'getSatsangCircle' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(SatsangCircle)],
        ['query'],
      ),
    'getShauchaPractice' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ShauchaPractice)],
        ['query'],
      ),
    'getSiddhi' : IDL.Func([IDL.Text], [IDL.Opt(SiddhiEntry)], ['query']),
    'getTarotCard' : IDL.Func([IDL.Text], [IDL.Opt(TarotCard)], ['query']),
    'getTransitCalendar' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TransitEvent)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getVerse' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Opt(Verse)], ['query']),
    'getVerseCommentary' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(VerseCommentary)],
        ['query'],
      ),
    'getWorshipStep' : IDL.Func([IDL.Text], [IDL.Opt(WorshipStep)], ['query']),
    'getYugCycle' : IDL.Func([IDL.Text], [IDL.Opt(YugCycle)], ['query']),
    'listChapters' : IDL.Func([], [IDL.Vec(Chapter)], ['query']),
    'listDailyDuties' : IDL.Func([], [IDL.Vec(DailyDuty)], ['query']),
    'listDevlokStages' : IDL.Func([], [IDL.Vec(DevlokStage)], ['query']),
    'listDharmaBodhSteps' : IDL.Func([], [IDL.Vec(DharmaBodhStep)], ['query']),
    'listDharmaPillars' : IDL.Func([], [IDL.Vec(DharmaPillar)], ['query']),
    'listGranthChapters' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(GranthChapter)],
        ['query'],
      ),
    'listGranthVerses' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Vec(GranthVerse)],
        ['query'],
      ),
    'listGranths' : IDL.Func([], [IDL.Vec(Granth)], ['query']),
    'listKalas' : IDL.Func([], [IDL.Vec(SiddhiEntry)], ['query']),
    'listKarmaTypes' : IDL.Func([], [IDL.Vec(KarmaType)], ['query']),
    'listLastRiteSteps' : IDL.Func([], [IDL.Vec(LastRiteStep)], ['query']),
    'listMahavidyas' : IDL.Func([], [IDL.Vec(SiddhiEntry)], ['query']),
    'listMaunaPractices' : IDL.Func([], [IDL.Vec(MaunaPractice)], ['query']),
    'listMokshaTeachings' : IDL.Func([], [IDL.Vec(MokshaTeaching)], ['query']),
    'listNewsletterSubscribers' : IDL.Func([], [IDL.Vec(EmailSubscriber)], []),
    'listNidhis' : IDL.Func([], [IDL.Vec(SiddhiEntry)], ['query']),
    'listPitruRites' : IDL.Func([], [IDL.Vec(PitruRite)], ['query']),
    'listPregnancyWeeks' : IDL.Func([], [IDL.Vec(PregnancyWeek)], ['query']),
    'listRitualExplanations' : IDL.Func(
        [],
        [IDL.Vec(RitualExplanation)],
        ['query'],
      ),
    'listSampradayas' : IDL.Func([], [IDL.Vec(Sampradaya)], ['query']),
    'listSanskaars' : IDL.Func([], [IDL.Vec(Sanskaar)], ['query']),
    'listSatsangCircleMetadata' : IDL.Func(
        [],
        [IDL.Vec(SatsangCircle)],
        ['query'],
      ),
    'listSatsangCircles' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'listShauchaPractices' : IDL.Func(
        [],
        [IDL.Vec(ShauchaPractice)],
        ['query'],
      ),
    'listSiddhis' : IDL.Func([], [IDL.Vec(SiddhiEntry)], ['query']),
    'listTarotCards' : IDL.Func([], [IDL.Vec(TarotCard)], ['query']),
    'listVerses' : IDL.Func([IDL.Nat], [IDL.Vec(Verse)], ['query']),
    'listWorshipSteps' : IDL.Func([], [IDL.Vec(WorshipStep)], ['query']),
    'listYugCycles' : IDL.Func([], [IDL.Vec(YugCycle)], ['query']),
    'postCircleMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'recordConcentrationSession' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [ConcentrationSession],
        [],
      ),
    'recordDailyReading' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Bool],
        [HeatmapEntry],
        [],
      ),
    'saveKundliData' : IDL.Func([KundliData], [IDL.Bool], []),
    'saveRemedyReminder' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'saveUserProfile' : IDL.Func([UserProfileInput], [IDL.Bool], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'searchJournalEntries' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(JournalEntry)],
        ['query'],
      ),
    'setDonationInfo' : IDL.Func([DonationInfoInput], [IDL.Bool], []),
    'setGalleryImageApproval' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
    'subscribeNewsletter' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'unsubscribeNewsletter' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'updateAdminConfig' : IDL.Func([AdminConfigInput], [IDL.Bool], []),
    'updateJournalEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Opt(JournalEntry)],
        [],
      ),
    'uploadGalleryImage' : IDL.Func([GalleryImageInput], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };