/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Chapter {
  'id' : bigint,
  'verseCount' : bigint,
  'name' : string,
  'summary' : string,
}
export interface ConcentrationSession {
  'id' : string,
  'completedAt' : bigint,
  'sessionType' : string,
  'durationMinutes' : bigint,
  'principalId' : string,
}
export interface DailyChallenge {
  'action' : string,
  'date' : string,
  'task' : string,
  'points' : bigint,
}
export interface Festival {
  'dateStr' : string,
  'meaning' : string,
  'name' : string,
  'mantraName' : string,
  'recommendedVerse' : string,
}
export interface GuidanceResult {
  'guidanceText' : string,
  'verse' : bigint,
  'keyword' : string,
  'chapter' : bigint,
}
export interface HeatmapEntry {
  'allGoalsMet' : boolean,
  'chaptersRead' : bigint,
  'date' : string,
  'versesRead' : bigint,
  'principalId' : string,
}
export interface JournalEntry {
  'id' : string,
  'mood' : string,
  'createdAt' : bigint,
  'text' : string,
  'verseId' : string,
  'updatedAt' : bigint,
  'principalId' : string,
}
export interface MantraEntry {
  'id' : string,
  'meaning' : string,
  'name' : string,
  'text' : string,
  'category' : string,
  'benefit' : string,
}
export interface SatsangMessage {
  'circleId' : string,
  'authorName' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface Verse {
  'id' : bigint,
  'verseNumber' : string,
  'sanskritText' : string,
  'chapterId' : bigint,
  'transliteration' : string,
  'englishTranslation' : string,
}
export interface VerseCommentary {
  'tilak' : string,
  'shankaracharya' : string,
  'verseId' : string,
  'ramanuja' : string,
}
export interface _SERVICE {
  'clearOldMessages' : ActorMethod<[], undefined>,
  'createJournalEntry' : ActorMethod<[string, string, string], JournalEntry>,
  'deleteJournalEntry' : ActorMethod<[string], boolean>,
  'getChapter' : ActorMethod<[bigint], [] | [Chapter]>,
  'getCircleMessages' : ActorMethod<[string], Array<SatsangMessage>>,
  'getConcentrationHistory' : ActorMethod<
    [bigint],
    Array<ConcentrationSession>
  >,
  'getDailyChallenge' : ActorMethod<[string], [] | [DailyChallenge]>,
  'getFestivals' : ActorMethod<[], Array<Festival>>,
  'getGuidanceByCategory' : ActorMethod<[string], [] | [GuidanceResult]>,
  'getHeatmapData' : ActorMethod<[bigint], Array<HeatmapEntry>>,
  'getJournalEntries' : ActorMethod<[], Array<JournalEntry>>,
  'getKrishnaGuidance' : ActorMethod<[string], [] | [GuidanceResult]>,
  'getMantras' : ActorMethod<[], Array<MantraEntry>>,
  'getReadingStreak' : ActorMethod<[], bigint>,
  'getVerse' : ActorMethod<[bigint, bigint], [] | [Verse]>,
  'getVerseCommentary' : ActorMethod<[string], [] | [VerseCommentary]>,
  'listChapters' : ActorMethod<[], Array<Chapter>>,
  'listSatsangCircles' : ActorMethod<[], Array<string>>,
  'listVerses' : ActorMethod<[bigint], Array<Verse>>,
  'postCircleMessage' : ActorMethod<[string, string, string], undefined>,
  'recordConcentrationSession' : ActorMethod<
    [bigint, string],
    ConcentrationSession
  >,
  'recordDailyReading' : ActorMethod<
    [string, bigint, bigint, boolean],
    HeatmapEntry
  >,
  'searchJournalEntries' : ActorMethod<[string], Array<JournalEntry>>,
  'updateJournalEntry' : ActorMethod<
    [string, string, string],
    [] | [JournalEntry]
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];