/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const GalleryImageMeta = IDL.Record({
  'id' : IDL.Nat,
  'isApproved' : IDL.Bool,
  'assetId' : IDL.Text,
  'caption' : IDL.Text,
  'category' : IDL.Text,
  'uploader' : IDL.Principal,
  'uploadedAt' : IDL.Int,
});
export const JournalEntry = IDL.Record({
  'id' : IDL.Text,
  'mood' : IDL.Text,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'verseId' : IDL.Text,
  'updatedAt' : IDL.Int,
  'principalId' : IDL.Text,
});
export const AdminConfig = IDL.Record({
  'newsletterEnabled' : IDL.Bool,
  'appVersion' : IDL.Text,
  'senderName' : IDL.Text,
  'senderEmail' : IDL.Text,
});
export const GrahaRemedyData = IDL.Record({
  'avoidList' : IDL.Vec(IDL.Text),
  'daan' : IDL.Text,
  'role' : IDL.Text,
  'mantraSanskrit' : IDL.Text,
  'mantraCount' : IDL.Nat,
  'gemstone' : IDL.Text,
  'graha' : IDL.Text,
  'weakCauses' : IDL.Vec(IDL.Text),
  'gemstoneWarning' : IDL.Text,
  'remedies' : IDL.Vec(IDL.Text),
  'strongGives' : IDL.Vec(IDL.Text),
});
export const Chapter = IDL.Record({
  'id' : IDL.Nat,
  'verseCount' : IDL.Nat,
  'name' : IDL.Text,
  'summary' : IDL.Text,
});
export const SatsangMessage = IDL.Record({
  'circleId' : IDL.Text,
  'authorName' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const ConcentrationSession = IDL.Record({
  'id' : IDL.Text,
  'completedAt' : IDL.Int,
  'sessionType' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'principalId' : IDL.Text,
});
export const DailyChallenge = IDL.Record({
  'action' : IDL.Text,
  'date' : IDL.Text,
  'task' : IDL.Text,
  'points' : IDL.Nat,
});
export const DonationInfo = IDL.Record({
  'qrCodeAssetId' : IDL.Text,
  'ifscCode' : IDL.Text,
  'bankName' : IDL.Text,
  'updatedAt' : IDL.Int,
  'accountName' : IDL.Text,
  'upiId' : IDL.Text,
  'accountNumber' : IDL.Text,
});
export const Festival = IDL.Record({
  'dateStr' : IDL.Text,
  'meaning' : IDL.Text,
  'name' : IDL.Text,
  'mantraName' : IDL.Text,
  'recommendedVerse' : IDL.Text,
});
export const GuidanceResult = IDL.Record({
  'guidanceText' : IDL.Text,
  'verse' : IDL.Nat,
  'keyword' : IDL.Text,
  'chapter' : IDL.Nat,
});
export const HeatmapEntry = IDL.Record({
  'allGoalsMet' : IDL.Bool,
  'chaptersRead' : IDL.Nat,
  'date' : IDL.Text,
  'versesRead' : IDL.Nat,
  'principalId' : IDL.Text,
});
export const DashaEntry = IDL.Record({
  'durationYears' : IDL.Float64,
  'endDate' : IDL.Int,
  'lord' : IDL.Text,
  'startDate' : IDL.Int,
});
export const PlanetPlacement = IDL.Record({
  'house' : IDL.Nat,
  'planet' : IDL.Text,
  'retrograde' : IDL.Bool,
  'sign' : IDL.Nat,
  'degree' : IDL.Float64,
  'nakshatra' : IDL.Text,
  'nakshatraLord' : IDL.Text,
});
export const KundliData = IDL.Record({
  'navamsaLagnaSign' : IDL.Nat,
  'pratyantarDasha' : DashaEntry,
  'lagnaRashi' : IDL.Text,
  'profileId' : IDL.Principal,
  'rulingPlanetGlyph' : IDL.Text,
  'lagnaSign' : IDL.Nat,
  'calculatedAt' : IDL.Int,
  'planets' : IDL.Vec(PlanetPlacement),
  'rulingPlanet' : IDL.Text,
  'antardasha' : DashaEntry,
  'navamsaPlanets' : IDL.Vec(PlanetPlacement),
  'nextDashas' : IDL.Vec(DashaEntry),
  'mahadasha' : DashaEntry,
});
export const MantraEntry = IDL.Record({
  'id' : IDL.Text,
  'meaning' : IDL.Text,
  'name' : IDL.Text,
  'text' : IDL.Text,
  'category' : IDL.Text,
  'benefit' : IDL.Text,
});
export const PanchangData = IDL.Record({
  'tithi' : IDL.Text,
  'vara' : IDL.Text,
  'yoga' : IDL.Text,
  'moonSign' : IDL.Text,
  'description' : IDL.Text,
  'nakshatra' : IDL.Text,
  'karana' : IDL.Text,
  'tithiNumber' : IDL.Nat,
});
export const RemedyReminder = IDL.Record({
  'isActive' : IDL.Bool,
  'reminderTime' : IDL.Text,
  'graha' : IDL.Text,
});
export const TransitEvent = IDL.Record({
  'remedy' : IDL.Text,
  'colorCode' : IDL.Text,
  'endDate' : IDL.Text,
  'planet' : IDL.Text,
  'description' : IDL.Text,
  'startDate' : IDL.Text,
  'eventType' : IDL.Text,
});
export const DateOfBirth = IDL.Record({
  'day' : IDL.Nat,
  'month' : IDL.Nat,
  'year' : IDL.Nat,
});
export const TimeOfBirth = IDL.Record({ 'hour' : IDL.Nat, 'minute' : IDL.Nat });
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'placeOfBirth' : IDL.Text,
  'latitude' : IDL.Float64,
  'timezone' : IDL.Text,
  'dateOfBirth' : DateOfBirth,
  'newsletterOptIn' : IDL.Bool,
  'createdAt' : IDL.Int,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'updatedAt' : IDL.Int,
  'timeOfBirth' : TimeOfBirth,
  'longitude' : IDL.Float64,
  'phone' : IDL.Text,
});
export const Verse = IDL.Record({
  'id' : IDL.Nat,
  'verseNumber' : IDL.Text,
  'sanskritText' : IDL.Text,
  'chapterId' : IDL.Nat,
  'transliteration' : IDL.Text,
  'englishTranslation' : IDL.Text,
});
export const VerseCommentary = IDL.Record({
  'tilak' : IDL.Text,
  'shankaracharya' : IDL.Text,
  'verseId' : IDL.Text,
  'ramanuja' : IDL.Text,
});
export const EmailSubscriber = IDL.Record({
  'active' : IDL.Bool,
  'subscribedAt' : IDL.Int,
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const UserProfileInput = IDL.Record({
  'placeOfBirth' : IDL.Text,
  'latitude' : IDL.Float64,
  'timezone' : IDL.Text,
  'dateOfBirth' : DateOfBirth,
  'newsletterOptIn' : IDL.Bool,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'timeOfBirth' : TimeOfBirth,
  'longitude' : IDL.Float64,
  'phone' : IDL.Text,
});
export const DonationInfoInput = IDL.Record({
  'qrCodeAssetId' : IDL.Text,
  'ifscCode' : IDL.Text,
  'bankName' : IDL.Text,
  'accountName' : IDL.Text,
  'upiId' : IDL.Text,
  'accountNumber' : IDL.Text,
});
export const AdminConfigInput = IDL.Record({
  'newsletterEnabled' : IDL.Bool,
  'appVersion' : IDL.Text,
  'senderName' : IDL.Text,
  'senderEmail' : IDL.Text,
});
export const GalleryImageInput = IDL.Record({
  'assetId' : IDL.Text,
  'caption' : IDL.Text,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'adminListAllGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImageMeta)], []),
  'clearOldMessages' : IDL.Func([], [], []),
  'createJournalEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [JournalEntry],
      [],
    ),
  'deleteJournalEntry' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getAdminConfig' : IDL.Func([], [AdminConfig], ['query']),
  'getAllGrahaRemedies' : IDL.Func([], [IDL.Vec(GrahaRemedyData)], ['query']),
  'getChapter' : IDL.Func([IDL.Nat], [IDL.Opt(Chapter)], ['query']),
  'getCircleMessages' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SatsangMessage)],
      ['query'],
    ),
  'getConcentrationHistory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ConcentrationSession)],
      ['query'],
    ),
  'getDailyChallenge' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DailyChallenge)],
      ['query'],
    ),
  'getDonationInfo' : IDL.Func([], [IDL.Opt(DonationInfo)], ['query']),
  'getFestivals' : IDL.Func([], [IDL.Vec(Festival)], ['query']),
  'getGalleryUploads' : IDL.Func([], [IDL.Vec(GalleryImageMeta)], ['query']),
  'getGrahaRemedy' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(GrahaRemedyData)],
      ['query'],
    ),
  'getGuidanceByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(GuidanceResult)],
      ['query'],
    ),
  'getHeatmapData' : IDL.Func([IDL.Nat], [IDL.Vec(HeatmapEntry)], ['query']),
  'getJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
  'getKrishnaGuidance' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(GuidanceResult)],
      ['query'],
    ),
  'getKundliData' : IDL.Func([], [IDL.Opt(KundliData)], ['query']),
  'getMantras' : IDL.Func([], [IDL.Vec(MantraEntry)], ['query']),
  'getPanchangToday' : IDL.Func([IDL.Text], [PanchangData], ['query']),
  'getReadingStreak' : IDL.Func([], [IDL.Nat], ['query']),
  'getRemedyReminder' : IDL.Func([], [IDL.Opt(RemedyReminder)], ['query']),
  'getTransitCalendar' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(TransitEvent)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getVerse' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Opt(Verse)], ['query']),
  'getVerseCommentary' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(VerseCommentary)],
      ['query'],
    ),
  'listChapters' : IDL.Func([], [IDL.Vec(Chapter)], ['query']),
  'listNewsletterSubscribers' : IDL.Func([], [IDL.Vec(EmailSubscriber)], []),
  'listSatsangCircles' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'listVerses' : IDL.Func([IDL.Nat], [IDL.Vec(Verse)], ['query']),
  'postCircleMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'recordConcentrationSession' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [ConcentrationSession],
      [],
    ),
  'recordDailyReading' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Bool],
      [HeatmapEntry],
      [],
    ),
  'saveKundliData' : IDL.Func([KundliData], [IDL.Bool], []),
  'saveRemedyReminder' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'saveUserProfile' : IDL.Func([UserProfileInput], [IDL.Bool], []),
  'searchJournalEntries' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(JournalEntry)],
      ['query'],
    ),
  'setDonationInfo' : IDL.Func([DonationInfoInput], [IDL.Bool], []),
  'setGalleryImageApproval' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
  'subscribeNewsletter' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  'unsubscribeNewsletter' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'updateAdminConfig' : IDL.Func([AdminConfigInput], [IDL.Bool], []),
  'updateJournalEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Opt(JournalEntry)],
      [],
    ),
  'uploadGalleryImage' : IDL.Func([GalleryImageInput], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const GalleryImageMeta = IDL.Record({
    'id' : IDL.Nat,
    'isApproved' : IDL.Bool,
    'assetId' : IDL.Text,
    'caption' : IDL.Text,
    'category' : IDL.Text,
    'uploader' : IDL.Principal,
    'uploadedAt' : IDL.Int,
  });
  const JournalEntry = IDL.Record({
    'id' : IDL.Text,
    'mood' : IDL.Text,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'verseId' : IDL.Text,
    'updatedAt' : IDL.Int,
    'principalId' : IDL.Text,
  });
  const AdminConfig = IDL.Record({
    'newsletterEnabled' : IDL.Bool,
    'appVersion' : IDL.Text,
    'senderName' : IDL.Text,
    'senderEmail' : IDL.Text,
  });
  const GrahaRemedyData = IDL.Record({
    'avoidList' : IDL.Vec(IDL.Text),
    'daan' : IDL.Text,
    'role' : IDL.Text,
    'mantraSanskrit' : IDL.Text,
    'mantraCount' : IDL.Nat,
    'gemstone' : IDL.Text,
    'graha' : IDL.Text,
    'weakCauses' : IDL.Vec(IDL.Text),
    'gemstoneWarning' : IDL.Text,
    'remedies' : IDL.Vec(IDL.Text),
    'strongGives' : IDL.Vec(IDL.Text),
  });
  const Chapter = IDL.Record({
    'id' : IDL.Nat,
    'verseCount' : IDL.Nat,
    'name' : IDL.Text,
    'summary' : IDL.Text,
  });
  const SatsangMessage = IDL.Record({
    'circleId' : IDL.Text,
    'authorName' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const ConcentrationSession = IDL.Record({
    'id' : IDL.Text,
    'completedAt' : IDL.Int,
    'sessionType' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'principalId' : IDL.Text,
  });
  const DailyChallenge = IDL.Record({
    'action' : IDL.Text,
    'date' : IDL.Text,
    'task' : IDL.Text,
    'points' : IDL.Nat,
  });
  const DonationInfo = IDL.Record({
    'qrCodeAssetId' : IDL.Text,
    'ifscCode' : IDL.Text,
    'bankName' : IDL.Text,
    'updatedAt' : IDL.Int,
    'accountName' : IDL.Text,
    'upiId' : IDL.Text,
    'accountNumber' : IDL.Text,
  });
  const Festival = IDL.Record({
    'dateStr' : IDL.Text,
    'meaning' : IDL.Text,
    'name' : IDL.Text,
    'mantraName' : IDL.Text,
    'recommendedVerse' : IDL.Text,
  });
  const GuidanceResult = IDL.Record({
    'guidanceText' : IDL.Text,
    'verse' : IDL.Nat,
    'keyword' : IDL.Text,
    'chapter' : IDL.Nat,
  });
  const HeatmapEntry = IDL.Record({
    'allGoalsMet' : IDL.Bool,
    'chaptersRead' : IDL.Nat,
    'date' : IDL.Text,
    'versesRead' : IDL.Nat,
    'principalId' : IDL.Text,
  });
  const DashaEntry = IDL.Record({
    'durationYears' : IDL.Float64,
    'endDate' : IDL.Int,
    'lord' : IDL.Text,
    'startDate' : IDL.Int,
  });
  const PlanetPlacement = IDL.Record({
    'house' : IDL.Nat,
    'planet' : IDL.Text,
    'retrograde' : IDL.Bool,
    'sign' : IDL.Nat,
    'degree' : IDL.Float64,
    'nakshatra' : IDL.Text,
    'nakshatraLord' : IDL.Text,
  });
  const KundliData = IDL.Record({
    'navamsaLagnaSign' : IDL.Nat,
    'pratyantarDasha' : DashaEntry,
    'lagnaRashi' : IDL.Text,
    'profileId' : IDL.Principal,
    'rulingPlanetGlyph' : IDL.Text,
    'lagnaSign' : IDL.Nat,
    'calculatedAt' : IDL.Int,
    'planets' : IDL.Vec(PlanetPlacement),
    'rulingPlanet' : IDL.Text,
    'antardasha' : DashaEntry,
    'navamsaPlanets' : IDL.Vec(PlanetPlacement),
    'nextDashas' : IDL.Vec(DashaEntry),
    'mahadasha' : DashaEntry,
  });
  const MantraEntry = IDL.Record({
    'id' : IDL.Text,
    'meaning' : IDL.Text,
    'name' : IDL.Text,
    'text' : IDL.Text,
    'category' : IDL.Text,
    'benefit' : IDL.Text,
  });
  const PanchangData = IDL.Record({
    'tithi' : IDL.Text,
    'vara' : IDL.Text,
    'yoga' : IDL.Text,
    'moonSign' : IDL.Text,
    'description' : IDL.Text,
    'nakshatra' : IDL.Text,
    'karana' : IDL.Text,
    'tithiNumber' : IDL.Nat,
  });
  const RemedyReminder = IDL.Record({
    'isActive' : IDL.Bool,
    'reminderTime' : IDL.Text,
    'graha' : IDL.Text,
  });
  const TransitEvent = IDL.Record({
    'remedy' : IDL.Text,
    'colorCode' : IDL.Text,
    'endDate' : IDL.Text,
    'planet' : IDL.Text,
    'description' : IDL.Text,
    'startDate' : IDL.Text,
    'eventType' : IDL.Text,
  });
  const DateOfBirth = IDL.Record({
    'day' : IDL.Nat,
    'month' : IDL.Nat,
    'year' : IDL.Nat,
  });
  const TimeOfBirth = IDL.Record({ 'hour' : IDL.Nat, 'minute' : IDL.Nat });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'placeOfBirth' : IDL.Text,
    'latitude' : IDL.Float64,
    'timezone' : IDL.Text,
    'dateOfBirth' : DateOfBirth,
    'newsletterOptIn' : IDL.Bool,
    'createdAt' : IDL.Int,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'updatedAt' : IDL.Int,
    'timeOfBirth' : TimeOfBirth,
    'longitude' : IDL.Float64,
    'phone' : IDL.Text,
  });
  const Verse = IDL.Record({
    'id' : IDL.Nat,
    'verseNumber' : IDL.Text,
    'sanskritText' : IDL.Text,
    'chapterId' : IDL.Nat,
    'transliteration' : IDL.Text,
    'englishTranslation' : IDL.Text,
  });
  const VerseCommentary = IDL.Record({
    'tilak' : IDL.Text,
    'shankaracharya' : IDL.Text,
    'verseId' : IDL.Text,
    'ramanuja' : IDL.Text,
  });
  const EmailSubscriber = IDL.Record({
    'active' : IDL.Bool,
    'subscribedAt' : IDL.Int,
    'name' : IDL.Text,
    'email' : IDL.Text,
  });
  const UserProfileInput = IDL.Record({
    'placeOfBirth' : IDL.Text,
    'latitude' : IDL.Float64,
    'timezone' : IDL.Text,
    'dateOfBirth' : DateOfBirth,
    'newsletterOptIn' : IDL.Bool,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'timeOfBirth' : TimeOfBirth,
    'longitude' : IDL.Float64,
    'phone' : IDL.Text,
  });
  const DonationInfoInput = IDL.Record({
    'qrCodeAssetId' : IDL.Text,
    'ifscCode' : IDL.Text,
    'bankName' : IDL.Text,
    'accountName' : IDL.Text,
    'upiId' : IDL.Text,
    'accountNumber' : IDL.Text,
  });
  const AdminConfigInput = IDL.Record({
    'newsletterEnabled' : IDL.Bool,
    'appVersion' : IDL.Text,
    'senderName' : IDL.Text,
    'senderEmail' : IDL.Text,
  });
  const GalleryImageInput = IDL.Record({
    'assetId' : IDL.Text,
    'caption' : IDL.Text,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'adminListAllGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImageMeta)], []),
    'clearOldMessages' : IDL.Func([], [], []),
    'createJournalEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [JournalEntry],
        [],
      ),
    'deleteJournalEntry' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getAdminConfig' : IDL.Func([], [AdminConfig], ['query']),
    'getAllGrahaRemedies' : IDL.Func([], [IDL.Vec(GrahaRemedyData)], ['query']),
    'getChapter' : IDL.Func([IDL.Nat], [IDL.Opt(Chapter)], ['query']),
    'getCircleMessages' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SatsangMessage)],
        ['query'],
      ),
    'getConcentrationHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ConcentrationSession)],
        ['query'],
      ),
    'getDailyChallenge' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DailyChallenge)],
        ['query'],
      ),
    'getDonationInfo' : IDL.Func([], [IDL.Opt(DonationInfo)], ['query']),
    'getFestivals' : IDL.Func([], [IDL.Vec(Festival)], ['query']),
    'getGalleryUploads' : IDL.Func([], [IDL.Vec(GalleryImageMeta)], ['query']),
    'getGrahaRemedy' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(GrahaRemedyData)],
        ['query'],
      ),
    'getGuidanceByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(GuidanceResult)],
        ['query'],
      ),
    'getHeatmapData' : IDL.Func([IDL.Nat], [IDL.Vec(HeatmapEntry)], ['query']),
    'getJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
    'getKrishnaGuidance' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(GuidanceResult)],
        ['query'],
      ),
    'getKundliData' : IDL.Func([], [IDL.Opt(KundliData)], ['query']),
    'getMantras' : IDL.Func([], [IDL.Vec(MantraEntry)], ['query']),
    'getPanchangToday' : IDL.Func([IDL.Text], [PanchangData], ['query']),
    'getReadingStreak' : IDL.Func([], [IDL.Nat], ['query']),
    'getRemedyReminder' : IDL.Func([], [IDL.Opt(RemedyReminder)], ['query']),
    'getTransitCalendar' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TransitEvent)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getVerse' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Opt(Verse)], ['query']),
    'getVerseCommentary' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(VerseCommentary)],
        ['query'],
      ),
    'listChapters' : IDL.Func([], [IDL.Vec(Chapter)], ['query']),
    'listNewsletterSubscribers' : IDL.Func([], [IDL.Vec(EmailSubscriber)], []),
    'listSatsangCircles' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'listVerses' : IDL.Func([IDL.Nat], [IDL.Vec(Verse)], ['query']),
    'postCircleMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'recordConcentrationSession' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [ConcentrationSession],
        [],
      ),
    'recordDailyReading' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Bool],
        [HeatmapEntry],
        [],
      ),
    'saveKundliData' : IDL.Func([KundliData], [IDL.Bool], []),
    'saveRemedyReminder' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'saveUserProfile' : IDL.Func([UserProfileInput], [IDL.Bool], []),
    'searchJournalEntries' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(JournalEntry)],
        ['query'],
      ),
    'setDonationInfo' : IDL.Func([DonationInfoInput], [IDL.Bool], []),
    'setGalleryImageApproval' : IDL.Func([IDL.Nat, IDL.Bool], [IDL.Bool], []),
    'subscribeNewsletter' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
    'unsubscribeNewsletter' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'updateAdminConfig' : IDL.Func([AdminConfigInput], [IDL.Bool], []),
    'updateJournalEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Opt(JournalEntry)],
        [],
      ),
    'uploadGalleryImage' : IDL.Func([GalleryImageInput], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };