/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const JournalEntry = IDL.Record({
  'id' : IDL.Text,
  'mood' : IDL.Text,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'verseId' : IDL.Text,
  'updatedAt' : IDL.Int,
  'principalId' : IDL.Text,
});
export const Chapter = IDL.Record({
  'id' : IDL.Nat,
  'verseCount' : IDL.Nat,
  'name' : IDL.Text,
  'summary' : IDL.Text,
});
export const SatsangMessage = IDL.Record({
  'circleId' : IDL.Text,
  'authorName' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const ConcentrationSession = IDL.Record({
  'id' : IDL.Text,
  'completedAt' : IDL.Int,
  'sessionType' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'principalId' : IDL.Text,
});
export const DailyChallenge = IDL.Record({
  'action' : IDL.Text,
  'date' : IDL.Text,
  'task' : IDL.Text,
  'points' : IDL.Nat,
});
export const Festival = IDL.Record({
  'dateStr' : IDL.Text,
  'meaning' : IDL.Text,
  'name' : IDL.Text,
  'mantraName' : IDL.Text,
  'recommendedVerse' : IDL.Text,
});
export const GuidanceResult = IDL.Record({
  'guidanceText' : IDL.Text,
  'verse' : IDL.Nat,
  'keyword' : IDL.Text,
  'chapter' : IDL.Nat,
});
export const HeatmapEntry = IDL.Record({
  'allGoalsMet' : IDL.Bool,
  'chaptersRead' : IDL.Nat,
  'date' : IDL.Text,
  'versesRead' : IDL.Nat,
  'principalId' : IDL.Text,
});
export const MantraEntry = IDL.Record({
  'id' : IDL.Text,
  'meaning' : IDL.Text,
  'name' : IDL.Text,
  'text' : IDL.Text,
  'category' : IDL.Text,
  'benefit' : IDL.Text,
});
export const Verse = IDL.Record({
  'id' : IDL.Nat,
  'verseNumber' : IDL.Text,
  'sanskritText' : IDL.Text,
  'chapterId' : IDL.Nat,
  'transliteration' : IDL.Text,
  'englishTranslation' : IDL.Text,
});
export const VerseCommentary = IDL.Record({
  'tilak' : IDL.Text,
  'shankaracharya' : IDL.Text,
  'verseId' : IDL.Text,
  'ramanuja' : IDL.Text,
});

export const idlService = IDL.Service({
  'clearOldMessages' : IDL.Func([], [], []),
  'createJournalEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [JournalEntry],
      [],
    ),
  'deleteJournalEntry' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'getChapter' : IDL.Func([IDL.Nat], [IDL.Opt(Chapter)], ['query']),
  'getCircleMessages' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(SatsangMessage)],
      ['query'],
    ),
  'getConcentrationHistory' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ConcentrationSession)],
      ['query'],
    ),
  'getDailyChallenge' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(DailyChallenge)],
      ['query'],
    ),
  'getFestivals' : IDL.Func([], [IDL.Vec(Festival)], ['query']),
  'getGuidanceByCategory' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(GuidanceResult)],
      ['query'],
    ),
  'getHeatmapData' : IDL.Func([IDL.Nat], [IDL.Vec(HeatmapEntry)], ['query']),
  'getJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
  'getKrishnaGuidance' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(GuidanceResult)],
      ['query'],
    ),
  'getMantras' : IDL.Func([], [IDL.Vec(MantraEntry)], ['query']),
  'getReadingStreak' : IDL.Func([], [IDL.Nat], ['query']),
  'getVerse' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Opt(Verse)], ['query']),
  'getVerseCommentary' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(VerseCommentary)],
      ['query'],
    ),
  'listChapters' : IDL.Func([], [IDL.Vec(Chapter)], ['query']),
  'listSatsangCircles' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'listVerses' : IDL.Func([IDL.Nat], [IDL.Vec(Verse)], ['query']),
  'postCircleMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'recordConcentrationSession' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [ConcentrationSession],
      [],
    ),
  'recordDailyReading' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Bool],
      [HeatmapEntry],
      [],
    ),
  'searchJournalEntries' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(JournalEntry)],
      ['query'],
    ),
  'updateJournalEntry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Opt(JournalEntry)],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const JournalEntry = IDL.Record({
    'id' : IDL.Text,
    'mood' : IDL.Text,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'verseId' : IDL.Text,
    'updatedAt' : IDL.Int,
    'principalId' : IDL.Text,
  });
  const Chapter = IDL.Record({
    'id' : IDL.Nat,
    'verseCount' : IDL.Nat,
    'name' : IDL.Text,
    'summary' : IDL.Text,
  });
  const SatsangMessage = IDL.Record({
    'circleId' : IDL.Text,
    'authorName' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const ConcentrationSession = IDL.Record({
    'id' : IDL.Text,
    'completedAt' : IDL.Int,
    'sessionType' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'principalId' : IDL.Text,
  });
  const DailyChallenge = IDL.Record({
    'action' : IDL.Text,
    'date' : IDL.Text,
    'task' : IDL.Text,
    'points' : IDL.Nat,
  });
  const Festival = IDL.Record({
    'dateStr' : IDL.Text,
    'meaning' : IDL.Text,
    'name' : IDL.Text,
    'mantraName' : IDL.Text,
    'recommendedVerse' : IDL.Text,
  });
  const GuidanceResult = IDL.Record({
    'guidanceText' : IDL.Text,
    'verse' : IDL.Nat,
    'keyword' : IDL.Text,
    'chapter' : IDL.Nat,
  });
  const HeatmapEntry = IDL.Record({
    'allGoalsMet' : IDL.Bool,
    'chaptersRead' : IDL.Nat,
    'date' : IDL.Text,
    'versesRead' : IDL.Nat,
    'principalId' : IDL.Text,
  });
  const MantraEntry = IDL.Record({
    'id' : IDL.Text,
    'meaning' : IDL.Text,
    'name' : IDL.Text,
    'text' : IDL.Text,
    'category' : IDL.Text,
    'benefit' : IDL.Text,
  });
  const Verse = IDL.Record({
    'id' : IDL.Nat,
    'verseNumber' : IDL.Text,
    'sanskritText' : IDL.Text,
    'chapterId' : IDL.Nat,
    'transliteration' : IDL.Text,
    'englishTranslation' : IDL.Text,
  });
  const VerseCommentary = IDL.Record({
    'tilak' : IDL.Text,
    'shankaracharya' : IDL.Text,
    'verseId' : IDL.Text,
    'ramanuja' : IDL.Text,
  });
  
  return IDL.Service({
    'clearOldMessages' : IDL.Func([], [], []),
    'createJournalEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [JournalEntry],
        [],
      ),
    'deleteJournalEntry' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'getChapter' : IDL.Func([IDL.Nat], [IDL.Opt(Chapter)], ['query']),
    'getCircleMessages' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(SatsangMessage)],
        ['query'],
      ),
    'getConcentrationHistory' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ConcentrationSession)],
        ['query'],
      ),
    'getDailyChallenge' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(DailyChallenge)],
        ['query'],
      ),
    'getFestivals' : IDL.Func([], [IDL.Vec(Festival)], ['query']),
    'getGuidanceByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(GuidanceResult)],
        ['query'],
      ),
    'getHeatmapData' : IDL.Func([IDL.Nat], [IDL.Vec(HeatmapEntry)], ['query']),
    'getJournalEntries' : IDL.Func([], [IDL.Vec(JournalEntry)], ['query']),
    'getKrishnaGuidance' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(GuidanceResult)],
        ['query'],
      ),
    'getMantras' : IDL.Func([], [IDL.Vec(MantraEntry)], ['query']),
    'getReadingStreak' : IDL.Func([], [IDL.Nat], ['query']),
    'getVerse' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Opt(Verse)], ['query']),
    'getVerseCommentary' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(VerseCommentary)],
        ['query'],
      ),
    'listChapters' : IDL.Func([], [IDL.Vec(Chapter)], ['query']),
    'listSatsangCircles' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'listVerses' : IDL.Func([IDL.Nat], [IDL.Vec(Verse)], ['query']),
    'postCircleMessage' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'recordConcentrationSession' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [ConcentrationSession],
        [],
      ),
    'recordDailyReading' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Bool],
        [HeatmapEntry],
        [],
      ),
    'searchJournalEntries' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(JournalEntry)],
        ['query'],
      ),
    'updateJournalEntry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Opt(JournalEntry)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };