/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SatsangMessage {
    circleId: string;
    authorName: string;
    message: string;
    timestamp: bigint;
}
export interface HeatmapEntry {
    allGoalsMet: boolean;
    chaptersRead: bigint;
    date: string;
    versesRead: bigint;
    principalId: string;
}
export interface VerseCommentary {
    tilak: string;
    shankaracharya: string;
    verseId: string;
    ramanuja: string;
}
export interface JournalEntry {
    id: string;
    mood: string;
    createdAt: bigint;
    text: string;
    verseId: string;
    updatedAt: bigint;
    principalId: string;
}
export interface GuidanceResult {
    guidanceText: string;
    verse: bigint;
    keyword: string;
    chapter: bigint;
}
export interface DailyChallenge {
    action: string;
    date: string;
    task: string;
    points: bigint;
}
export interface Verse {
    id: bigint;
    verseNumber: string;
    sanskritText: string;
    chapterId: bigint;
    transliteration: string;
    englishTranslation: string;
}
export interface Festival {
    dateStr: string;
    meaning: string;
    name: string;
    mantraName: string;
    recommendedVerse: string;
}
export interface ConcentrationSession {
    id: string;
    completedAt: bigint;
    sessionType: string;
    durationMinutes: bigint;
    principalId: string;
}
export interface MantraEntry {
    id: string;
    meaning: string;
    name: string;
    text: string;
    category: string;
    benefit: string;
}
export interface Chapter {
    id: bigint;
    verseCount: bigint;
    name: string;
    summary: string;
}
export interface backendInterface {
    clearOldMessages(): Promise<void>;
    createJournalEntry(verseId: string, text: string, mood: string): Promise<JournalEntry>;
    deleteJournalEntry(id: string): Promise<boolean>;
    getChapter(chapterId: bigint): Promise<Chapter | null>;
    getCircleMessages(circleId: string): Promise<Array<SatsangMessage>>;
    getConcentrationHistory(limit: bigint): Promise<Array<ConcentrationSession>>;
    getDailyChallenge(dateKey: string): Promise<DailyChallenge | null>;
    getFestivals(): Promise<Array<Festival>>;
    getGuidanceByCategory(category: string): Promise<GuidanceResult | null>;
    getHeatmapData(days: bigint): Promise<Array<HeatmapEntry>>;
    getJournalEntries(): Promise<Array<JournalEntry>>;
    getKrishnaGuidance(keyword: string): Promise<GuidanceResult | null>;
    getMantras(): Promise<Array<MantraEntry>>;
    getReadingStreak(): Promise<bigint>;
    getVerse(chapterId: bigint, verseId: bigint): Promise<Verse | null>;
    getVerseCommentary(verseId: string): Promise<VerseCommentary | null>;
    listChapters(): Promise<Array<Chapter>>;
    listSatsangCircles(): Promise<Array<string>>;
    listVerses(chapterId: bigint): Promise<Array<Verse>>;
    postCircleMessage(circleId: string, authorName: string, message: string): Promise<void>;
    recordConcentrationSession(durationMinutes: bigint, sessionType: string): Promise<ConcentrationSession>;
    recordDailyReading(date: string, versesRead: bigint, chaptersRead: bigint, allGoalsMet: boolean): Promise<HeatmapEntry>;
    searchJournalEntries(searchText: string): Promise<Array<JournalEntry>>;
    updateJournalEntry(id: string, text: string, mood: string): Promise<JournalEntry | null>;
}
import type { Chapter as _Chapter, DailyChallenge as _DailyChallenge, GuidanceResult as _GuidanceResult, JournalEntry as _JournalEntry, Verse as _Verse, VerseCommentary as _VerseCommentary } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async clearOldMessages(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearOldMessages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearOldMessages();
            return result;
        }
    }
    async createJournalEntry(arg0: string, arg1: string, arg2: string): Promise<JournalEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.createJournalEntry(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJournalEntry(arg0, arg1, arg2);
            return result;
        }
    }
    async deleteJournalEntry(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteJournalEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteJournalEntry(arg0);
            return result;
        }
    }
    async getChapter(arg0: bigint): Promise<Chapter | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChapter(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChapter(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCircleMessages(arg0: string): Promise<Array<SatsangMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCircleMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCircleMessages(arg0);
            return result;
        }
    }
    async getConcentrationHistory(arg0: bigint): Promise<Array<ConcentrationSession>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConcentrationHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConcentrationHistory(arg0);
            return result;
        }
    }
    async getDailyChallenge(arg0: string): Promise<DailyChallenge | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDailyChallenge(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDailyChallenge(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFestivals(): Promise<Array<Festival>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFestivals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFestivals();
            return result;
        }
    }
    async getGuidanceByCategory(arg0: string): Promise<GuidanceResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGuidanceByCategory(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGuidanceByCategory(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHeatmapData(arg0: bigint): Promise<Array<HeatmapEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHeatmapData(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHeatmapData(arg0);
            return result;
        }
    }
    async getJournalEntries(): Promise<Array<JournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJournalEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJournalEntries();
            return result;
        }
    }
    async getKrishnaGuidance(arg0: string): Promise<GuidanceResult | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getKrishnaGuidance(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getKrishnaGuidance(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMantras(): Promise<Array<MantraEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMantras();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMantras();
            return result;
        }
    }
    async getReadingStreak(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getReadingStreak();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReadingStreak();
            return result;
        }
    }
    async getVerse(arg0: bigint, arg1: bigint): Promise<Verse | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVerse(arg0, arg1);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVerse(arg0, arg1);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVerseCommentary(arg0: string): Promise<VerseCommentary | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVerseCommentary(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVerseCommentary(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async listChapters(): Promise<Array<Chapter>> {
        if (this.processError) {
            try {
                const result = await this.actor.listChapters();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listChapters();
            return result;
        }
    }
    async listSatsangCircles(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.listSatsangCircles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listSatsangCircles();
            return result;
        }
    }
    async listVerses(arg0: bigint): Promise<Array<Verse>> {
        if (this.processError) {
            try {
                const result = await this.actor.listVerses(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listVerses(arg0);
            return result;
        }
    }
    async postCircleMessage(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.postCircleMessage(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.postCircleMessage(arg0, arg1, arg2);
            return result;
        }
    }
    async recordConcentrationSession(arg0: bigint, arg1: string): Promise<ConcentrationSession> {
        if (this.processError) {
            try {
                const result = await this.actor.recordConcentrationSession(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordConcentrationSession(arg0, arg1);
            return result;
        }
    }
    async recordDailyReading(arg0: string, arg1: bigint, arg2: bigint, arg3: boolean): Promise<HeatmapEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.recordDailyReading(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordDailyReading(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async searchJournalEntries(arg0: string): Promise<Array<JournalEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchJournalEntries(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchJournalEntries(arg0);
            return result;
        }
    }
    async updateJournalEntry(arg0: string, arg1: string, arg2: string): Promise<JournalEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateJournalEntry(arg0, arg1, arg2);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateJournalEntry(arg0, arg1, arg2);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Chapter]): Chapter | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_DailyChallenge]): DailyChallenge | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GuidanceResult]): GuidanceResult | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Verse]): Verse | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_VerseCommentary]): VerseCommentary | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JournalEntry]): JournalEntry | null {
    return value.length === 0 ? null : value[0];
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
